# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from tester.app.dto.base_model_ import Model
from tester.app.dto.current_account_sd_reference_id_current_account_fulfillment_arrangement_cr_reference_id_accountsweep_bq_reference_id_update_account_sweep_instance_record_sweep_application_record import CurrentAccountSdReferenceIdCurrentAccountFulfillmentArrangementCrReferenceIdAccountsweepBqReferenceIdUpdateAccountSweepInstanceRecordSweepApplicationRecord
from tester.app.dto.current_account_sd_reference_id_current_account_fulfillment_arrangement_cr_reference_id_accountsweep_initiation_account_sweep_instance_record_account_sweep_configuration import CurrentAccountSdReferenceIdCurrentAccountFulfillmentArrangementCrReferenceIdAccountsweepInitiationAccountSweepInstanceRecordAccountSweepConfiguration
from tester import util

from tester.app.dto.current_account_sd_reference_id_current_account_fulfillment_arrangement_cr_reference_id_accountsweep_bq_reference_id_update_account_sweep_instance_record_sweep_application_record import CurrentAccountSdReferenceIdCurrentAccountFulfillmentArrangementCrReferenceIdAccountsweepBqReferenceIdUpdateAccountSweepInstanceRecordSweepApplicationRecord  # noqa: E501
from tester.app.dto.current_account_sd_reference_id_current_account_fulfillment_arrangement_cr_reference_id_accountsweep_initiation_account_sweep_instance_record_account_sweep_configuration import CurrentAccountSdReferenceIdCurrentAccountFulfillmentArrangementCrReferenceIdAccountsweepInitiationAccountSweepInstanceRecordAccountSweepConfiguration  # noqa: E501



class BQAccountSweepUpdateInputModelAccountSweepInstanceRecord(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, account_sweep_type=None, account_sweep_definition=None, account_sweep_application_schedule=None, account_sweep_configuration=None, sweep_application_record=None):  # noqa: E501
        """BQAccountSweepUpdateInputModelAccountSweepInstanceRecord - a model defined in OpenAPI

        :param account_sweep_type: The account_sweep_type of this BQAccountSweepUpdateInputModelAccountSweepInstanceRecord.  # noqa: E501
        :type account_sweep_type: str
        :param account_sweep_definition: The account_sweep_definition of this BQAccountSweepUpdateInputModelAccountSweepInstanceRecord.  # noqa: E501
        :type account_sweep_definition: str
        :param account_sweep_application_schedule: The account_sweep_application_schedule of this BQAccountSweepUpdateInputModelAccountSweepInstanceRecord.  # noqa: E501
        :type account_sweep_application_schedule: str
        :param account_sweep_configuration: The account_sweep_configuration of this BQAccountSweepUpdateInputModelAccountSweepInstanceRecord.  # noqa: E501
        :type account_sweep_configuration: CurrentAccountSdReferenceIdCurrentAccountFulfillmentArrangementCrReferenceIdAccountsweepInitiationAccountSweepInstanceRecordAccountSweepConfiguration
        :param sweep_application_record: The sweep_application_record of this BQAccountSweepUpdateInputModelAccountSweepInstanceRecord.  # noqa: E501
        :type sweep_application_record: CurrentAccountSdReferenceIdCurrentAccountFulfillmentArrangementCrReferenceIdAccountsweepBqReferenceIdUpdateAccountSweepInstanceRecordSweepApplicationRecord
        """
        self.openapi_types = {
            'account_sweep_type': str,
            'account_sweep_definition': str,
            'account_sweep_application_schedule': str,
            'account_sweep_configuration': CurrentAccountSdReferenceIdCurrentAccountFulfillmentArrangementCrReferenceIdAccountsweepInitiationAccountSweepInstanceRecordAccountSweepConfiguration,
            'sweep_application_record': CurrentAccountSdReferenceIdCurrentAccountFulfillmentArrangementCrReferenceIdAccountsweepBqReferenceIdUpdateAccountSweepInstanceRecordSweepApplicationRecord
        }

        self.attribute_map = {
            'account_sweep_type': 'accountSweepType',
            'account_sweep_definition': 'accountSweepDefinition',
            'account_sweep_application_schedule': 'accountSweepApplicationSchedule',
            'account_sweep_configuration': 'accountSweepConfiguration',
            'sweep_application_record': 'sweepApplicationRecord'
        }

        self._account_sweep_type = account_sweep_type
        self._account_sweep_definition = account_sweep_definition
        self._account_sweep_application_schedule = account_sweep_application_schedule
        self._account_sweep_configuration = account_sweep_configuration
        self._sweep_application_record = sweep_application_record

    @classmethod
    def from_dict(cls, dikt) -> 'BQAccountSweepUpdateInputModelAccountSweepInstanceRecord':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The BQAccountSweepUpdateInputModel_accountSweepInstanceRecord of this BQAccountSweepUpdateInputModelAccountSweepInstanceRecord.  # noqa: E501
        :rtype: BQAccountSweepUpdateInputModelAccountSweepInstanceRecord
        """
        return util.deserialize_model(dikt, cls)

    @property
    def account_sweep_type(self):
        """Gets the account_sweep_type of this BQAccountSweepUpdateInputModelAccountSweepInstanceRecord.

        `status: Not Mapped`  core-data-type-reference: BIAN::DataTypesLibrary::CoreDataTypes::UNCEFACT::Text  general-info: The type of sweep (e.g. periodic, threshold)   # noqa: E501

        :return: The account_sweep_type of this BQAccountSweepUpdateInputModelAccountSweepInstanceRecord.
        :rtype: str
        """
        return self._account_sweep_type

    @account_sweep_type.setter
    def account_sweep_type(self, account_sweep_type):
        """Sets the account_sweep_type of this BQAccountSweepUpdateInputModelAccountSweepInstanceRecord.

        `status: Not Mapped`  core-data-type-reference: BIAN::DataTypesLibrary::CoreDataTypes::UNCEFACT::Text  general-info: The type of sweep (e.g. periodic, threshold)   # noqa: E501

        :param account_sweep_type: The account_sweep_type of this BQAccountSweepUpdateInputModelAccountSweepInstanceRecord.
        :type account_sweep_type: str
        """

        self._account_sweep_type = account_sweep_type

    @property
    def account_sweep_definition(self):
        """Gets the account_sweep_definition of this BQAccountSweepUpdateInputModelAccountSweepInstanceRecord.

        `status: Not Mapped`  core-data-type-reference: BIAN::DataTypesLibrary::CoreDataTypes::UNCEFACT::Text  general-info: Definition of the type of sweep   # noqa: E501

        :return: The account_sweep_definition of this BQAccountSweepUpdateInputModelAccountSweepInstanceRecord.
        :rtype: str
        """
        return self._account_sweep_definition

    @account_sweep_definition.setter
    def account_sweep_definition(self, account_sweep_definition):
        """Sets the account_sweep_definition of this BQAccountSweepUpdateInputModelAccountSweepInstanceRecord.

        `status: Not Mapped`  core-data-type-reference: BIAN::DataTypesLibrary::CoreDataTypes::UNCEFACT::Text  general-info: Definition of the type of sweep   # noqa: E501

        :param account_sweep_definition: The account_sweep_definition of this BQAccountSweepUpdateInputModelAccountSweepInstanceRecord.
        :type account_sweep_definition: str
        """

        self._account_sweep_definition = account_sweep_definition

    @property
    def account_sweep_application_schedule(self):
        """Gets the account_sweep_application_schedule of this BQAccountSweepUpdateInputModelAccountSweepInstanceRecord.

        `status: Not Mapped`  core-data-type-reference: BIAN::DataTypesLibrary::CoreDataTypes::UNCEFACT::Text  general-info: Sweep processing guidelines and scheduling rules   # noqa: E501

        :return: The account_sweep_application_schedule of this BQAccountSweepUpdateInputModelAccountSweepInstanceRecord.
        :rtype: str
        """
        return self._account_sweep_application_schedule

    @account_sweep_application_schedule.setter
    def account_sweep_application_schedule(self, account_sweep_application_schedule):
        """Sets the account_sweep_application_schedule of this BQAccountSweepUpdateInputModelAccountSweepInstanceRecord.

        `status: Not Mapped`  core-data-type-reference: BIAN::DataTypesLibrary::CoreDataTypes::UNCEFACT::Text  general-info: Sweep processing guidelines and scheduling rules   # noqa: E501

        :param account_sweep_application_schedule: The account_sweep_application_schedule of this BQAccountSweepUpdateInputModelAccountSweepInstanceRecord.
        :type account_sweep_application_schedule: str
        """

        self._account_sweep_application_schedule = account_sweep_application_schedule

    @property
    def account_sweep_configuration(self):
        """Gets the account_sweep_configuration of this BQAccountSweepUpdateInputModelAccountSweepInstanceRecord.


        :return: The account_sweep_configuration of this BQAccountSweepUpdateInputModelAccountSweepInstanceRecord.
        :rtype: CurrentAccountSdReferenceIdCurrentAccountFulfillmentArrangementCrReferenceIdAccountsweepInitiationAccountSweepInstanceRecordAccountSweepConfiguration
        """
        return self._account_sweep_configuration

    @account_sweep_configuration.setter
    def account_sweep_configuration(self, account_sweep_configuration):
        """Sets the account_sweep_configuration of this BQAccountSweepUpdateInputModelAccountSweepInstanceRecord.


        :param account_sweep_configuration: The account_sweep_configuration of this BQAccountSweepUpdateInputModelAccountSweepInstanceRecord.
        :type account_sweep_configuration: CurrentAccountSdReferenceIdCurrentAccountFulfillmentArrangementCrReferenceIdAccountsweepInitiationAccountSweepInstanceRecordAccountSweepConfiguration
        """

        self._account_sweep_configuration = account_sweep_configuration

    @property
    def sweep_application_record(self):
        """Gets the sweep_application_record of this BQAccountSweepUpdateInputModelAccountSweepInstanceRecord.


        :return: The sweep_application_record of this BQAccountSweepUpdateInputModelAccountSweepInstanceRecord.
        :rtype: CurrentAccountSdReferenceIdCurrentAccountFulfillmentArrangementCrReferenceIdAccountsweepBqReferenceIdUpdateAccountSweepInstanceRecordSweepApplicationRecord
        """
        return self._sweep_application_record

    @sweep_application_record.setter
    def sweep_application_record(self, sweep_application_record):
        """Sets the sweep_application_record of this BQAccountSweepUpdateInputModelAccountSweepInstanceRecord.


        :param sweep_application_record: The sweep_application_record of this BQAccountSweepUpdateInputModelAccountSweepInstanceRecord.
        :type sweep_application_record: CurrentAccountSdReferenceIdCurrentAccountFulfillmentArrangementCrReferenceIdAccountsweepBqReferenceIdUpdateAccountSweepInstanceRecordSweepApplicationRecord
        """

        self._sweep_application_record = sweep_application_record
