# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from tester.app.dto.base_model_ import Model
from tester import util




class BQAccountLienInitiateInputModelCurrentAccountFulfillmentArrangementInstanceRecordPositionLimits(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, position_limit_type=None, position_limit_settings=None):  # noqa: E501
        """BQAccountLienInitiateInputModelCurrentAccountFulfillmentArrangementInstanceRecordPositionLimits - a model defined in OpenAPI

        :param position_limit_type: The position_limit_type of this BQAccountLienInitiateInputModelCurrentAccountFulfillmentArrangementInstanceRecordPositionLimits.  # noqa: E501
        :type position_limit_type: str
        :param position_limit_settings: The position_limit_settings of this BQAccountLienInitiateInputModelCurrentAccountFulfillmentArrangementInstanceRecordPositionLimits.  # noqa: E501
        :type position_limit_settings: str
        """
        self.openapi_types = {
            'position_limit_type': str,
            'position_limit_settings': str
        }

        self.attribute_map = {
            'position_limit_type': 'positionLimitType',
            'position_limit_settings': 'positionLimitSettings'
        }

        self._position_limit_type = position_limit_type
        self._position_limit_settings = position_limit_settings

    @classmethod
    def from_dict(cls, dikt) -> 'BQAccountLienInitiateInputModelCurrentAccountFulfillmentArrangementInstanceRecordPositionLimits':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The BQAccountLienInitiateInputModel_currentAccountFulfillmentArrangementInstanceRecord_positionLimits of this BQAccountLienInitiateInputModelCurrentAccountFulfillmentArrangementInstanceRecordPositionLimits.  # noqa: E501
        :rtype: BQAccountLienInitiateInputModelCurrentAccountFulfillmentArrangementInstanceRecordPositionLimits
        """
        return util.deserialize_model(dikt, cls)

    @property
    def position_limit_type(self):
        """Gets the position_limit_type of this BQAccountLienInitiateInputModelCurrentAccountFulfillmentArrangementInstanceRecordPositionLimits.

        `status: Not Mapped`  core-data-type-reference: BIAN::DataTypesLibrary::CoreDataTypes::UNCEFACT::Text  general-info: The type of position maintained for the account (e.g. transaction credit/debit, netting, position)   # noqa: E501

        :return: The position_limit_type of this BQAccountLienInitiateInputModelCurrentAccountFulfillmentArrangementInstanceRecordPositionLimits.
        :rtype: str
        """
        return self._position_limit_type

    @position_limit_type.setter
    def position_limit_type(self, position_limit_type):
        """Sets the position_limit_type of this BQAccountLienInitiateInputModelCurrentAccountFulfillmentArrangementInstanceRecordPositionLimits.

        `status: Not Mapped`  core-data-type-reference: BIAN::DataTypesLibrary::CoreDataTypes::UNCEFACT::Text  general-info: The type of position maintained for the account (e.g. transaction credit/debit, netting, position)   # noqa: E501

        :param position_limit_type: The position_limit_type of this BQAccountLienInitiateInputModelCurrentAccountFulfillmentArrangementInstanceRecordPositionLimits.
        :type position_limit_type: str
        """

        self._position_limit_type = position_limit_type

    @property
    def position_limit_settings(self):
        """Gets the position_limit_settings of this BQAccountLienInitiateInputModelCurrentAccountFulfillmentArrangementInstanceRecordPositionLimits.

        `status: Not Mapped`  core-data-type-reference: BIAN::DataTypesLibrary::CoreDataTypes::UNCEFACT::Text  general-info: The position definition, associated limit settings and rules   # noqa: E501

        :return: The position_limit_settings of this BQAccountLienInitiateInputModelCurrentAccountFulfillmentArrangementInstanceRecordPositionLimits.
        :rtype: str
        """
        return self._position_limit_settings

    @position_limit_settings.setter
    def position_limit_settings(self, position_limit_settings):
        """Sets the position_limit_settings of this BQAccountLienInitiateInputModelCurrentAccountFulfillmentArrangementInstanceRecordPositionLimits.

        `status: Not Mapped`  core-data-type-reference: BIAN::DataTypesLibrary::CoreDataTypes::UNCEFACT::Text  general-info: The position definition, associated limit settings and rules   # noqa: E501

        :param position_limit_settings: The position_limit_settings of this BQAccountLienInitiateInputModelCurrentAccountFulfillmentArrangementInstanceRecordPositionLimits.
        :type position_limit_settings: str
        """

        self._position_limit_settings = position_limit_settings
