# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from tester.app.dto.base_model_ import Model
from tester import util




class BQAccountSweepRetrieveInputModelAccountSweepInstanceAnalysis(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, account_sweep_instance_analysis_reference=None):  # noqa: E501
        """BQAccountSweepRetrieveInputModelAccountSweepInstanceAnalysis - a model defined in OpenAPI

        :param account_sweep_instance_analysis_reference: The account_sweep_instance_analysis_reference of this BQAccountSweepRetrieveInputModelAccountSweepInstanceAnalysis.  # noqa: E501
        :type account_sweep_instance_analysis_reference: str
        """
        self.openapi_types = {
            'account_sweep_instance_analysis_reference': str
        }

        self.attribute_map = {
            'account_sweep_instance_analysis_reference': 'accountSweepInstanceAnalysisReference'
        }

        self._account_sweep_instance_analysis_reference = account_sweep_instance_analysis_reference

    @classmethod
    def from_dict(cls, dikt) -> 'BQAccountSweepRetrieveInputModelAccountSweepInstanceAnalysis':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The BQAccountSweepRetrieveInputModel_accountSweepInstanceAnalysis of this BQAccountSweepRetrieveInputModelAccountSweepInstanceAnalysis.  # noqa: E501
        :rtype: BQAccountSweepRetrieveInputModelAccountSweepInstanceAnalysis
        """
        return util.deserialize_model(dikt, cls)

    @property
    def account_sweep_instance_analysis_reference(self):
        """Gets the account_sweep_instance_analysis_reference of this BQAccountSweepRetrieveInputModelAccountSweepInstanceAnalysis.

        `status: Not Mapped`  core-data-type-reference: BIAN::DataTypesLibrary::CoreDataTypes::ISO20022andUNCEFACT::Identifier  general-info: Reference to the control record instance analysis view   # noqa: E501

        :return: The account_sweep_instance_analysis_reference of this BQAccountSweepRetrieveInputModelAccountSweepInstanceAnalysis.
        :rtype: str
        """
        return self._account_sweep_instance_analysis_reference

    @account_sweep_instance_analysis_reference.setter
    def account_sweep_instance_analysis_reference(self, account_sweep_instance_analysis_reference):
        """Sets the account_sweep_instance_analysis_reference of this BQAccountSweepRetrieveInputModelAccountSweepInstanceAnalysis.

        `status: Not Mapped`  core-data-type-reference: BIAN::DataTypesLibrary::CoreDataTypes::ISO20022andUNCEFACT::Identifier  general-info: Reference to the control record instance analysis view   # noqa: E501

        :param account_sweep_instance_analysis_reference: The account_sweep_instance_analysis_reference of this BQAccountSweepRetrieveInputModelAccountSweepInstanceAnalysis.
        :type account_sweep_instance_analysis_reference: str
        """

        self._account_sweep_instance_analysis_reference = account_sweep_instance_analysis_reference
