# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from tester.app.dto.base_model_ import Model
from tester.app.dto.current_account_sd_reference_id_current_account_fulfillment_arrangement_cr_reference_id_depositsandwithdrawals_bq_reference_id_execution_deposits_and_withdrawals_instance_record import CurrentAccountSdReferenceIdCurrentAccountFulfillmentArrangementCrReferenceIdDepositsandwithdrawalsBqReferenceIdExecutionDepositsAndWithdrawalsInstanceRecord
from tester.app.dto.current_account_sd_reference_id_current_account_fulfillment_arrangement_cr_reference_id_servicefees_bq_reference_id_execution_execute_record_type import CurrentAccountSdReferenceIdCurrentAccountFulfillmentArrangementCrReferenceIdServicefeesBqReferenceIdExecutionExecuteRecordType
from tester import util

from tester.app.dto.current_account_sd_reference_id_current_account_fulfillment_arrangement_cr_reference_id_depositsandwithdrawals_bq_reference_id_execution_deposits_and_withdrawals_instance_record import CurrentAccountSdReferenceIdCurrentAccountFulfillmentArrangementCrReferenceIdDepositsandwithdrawalsBqReferenceIdExecutionDepositsAndWithdrawalsInstanceRecord  # noqa: E501
from tester.app.dto.current_account_sd_reference_id_current_account_fulfillment_arrangement_cr_reference_id_servicefees_bq_reference_id_execution_execute_record_type import CurrentAccountSdReferenceIdCurrentAccountFulfillmentArrangementCrReferenceIdServicefeesBqReferenceIdExecutionExecuteRecordType  # noqa: E501



class BQDepositsAndWithdrawalsExecuteInputModel(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, current_account_fulfillment_arrangement_instance_reference=None, deposits_and_withdrawals_instance_reference=None, deposits_and_withdrawals_instance_record=None, deposits_and_withdrawals_execute_action_task_record=None, execute_record_type=None):  # noqa: E501
        """BQDepositsAndWithdrawalsExecuteInputModel - a model defined in OpenAPI

        :param current_account_fulfillment_arrangement_instance_reference: The current_account_fulfillment_arrangement_instance_reference of this BQDepositsAndWithdrawalsExecuteInputModel.  # noqa: E501
        :type current_account_fulfillment_arrangement_instance_reference: str
        :param deposits_and_withdrawals_instance_reference: The deposits_and_withdrawals_instance_reference of this BQDepositsAndWithdrawalsExecuteInputModel.  # noqa: E501
        :type deposits_and_withdrawals_instance_reference: str
        :param deposits_and_withdrawals_instance_record: The deposits_and_withdrawals_instance_record of this BQDepositsAndWithdrawalsExecuteInputModel.  # noqa: E501
        :type deposits_and_withdrawals_instance_record: CurrentAccountSdReferenceIdCurrentAccountFulfillmentArrangementCrReferenceIdDepositsandwithdrawalsBqReferenceIdExecutionDepositsAndWithdrawalsInstanceRecord
        :param deposits_and_withdrawals_execute_action_task_record: The deposits_and_withdrawals_execute_action_task_record of this BQDepositsAndWithdrawalsExecuteInputModel.  # noqa: E501
        :type deposits_and_withdrawals_execute_action_task_record: object
        :param execute_record_type: The execute_record_type of this BQDepositsAndWithdrawalsExecuteInputModel.  # noqa: E501
        :type execute_record_type: CurrentAccountSdReferenceIdCurrentAccountFulfillmentArrangementCrReferenceIdServicefeesBqReferenceIdExecutionExecuteRecordType
        """
        self.openapi_types = {
            'current_account_fulfillment_arrangement_instance_reference': str,
            'deposits_and_withdrawals_instance_reference': str,
            'deposits_and_withdrawals_instance_record': CurrentAccountSdReferenceIdCurrentAccountFulfillmentArrangementCrReferenceIdDepositsandwithdrawalsBqReferenceIdExecutionDepositsAndWithdrawalsInstanceRecord,
            'deposits_and_withdrawals_execute_action_task_record': object,
            'execute_record_type': CurrentAccountSdReferenceIdCurrentAccountFulfillmentArrangementCrReferenceIdServicefeesBqReferenceIdExecutionExecuteRecordType
        }

        self.attribute_map = {
            'current_account_fulfillment_arrangement_instance_reference': 'currentAccountFulfillmentArrangementInstanceReference',
            'deposits_and_withdrawals_instance_reference': 'depositsAndWithdrawalsInstanceReference',
            'deposits_and_withdrawals_instance_record': 'depositsAndWithdrawalsInstanceRecord',
            'deposits_and_withdrawals_execute_action_task_record': 'depositsAndWithdrawalsExecuteActionTaskRecord',
            'execute_record_type': 'executeRecordType'
        }

        self._current_account_fulfillment_arrangement_instance_reference = current_account_fulfillment_arrangement_instance_reference
        self._deposits_and_withdrawals_instance_reference = deposits_and_withdrawals_instance_reference
        self._deposits_and_withdrawals_instance_record = deposits_and_withdrawals_instance_record
        self._deposits_and_withdrawals_execute_action_task_record = deposits_and_withdrawals_execute_action_task_record
        self._execute_record_type = execute_record_type

    @classmethod
    def from_dict(cls, dikt) -> 'BQDepositsAndWithdrawalsExecuteInputModel':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The BQDepositsAndWithdrawalsExecuteInputModel of this BQDepositsAndWithdrawalsExecuteInputModel.  # noqa: E501
        :rtype: BQDepositsAndWithdrawalsExecuteInputModel
        """
        return util.deserialize_model(dikt, cls)

    @property
    def current_account_fulfillment_arrangement_instance_reference(self):
        """Gets the current_account_fulfillment_arrangement_instance_reference of this BQDepositsAndWithdrawalsExecuteInputModel.

        `status: Not Mapped`  core-data-type-reference: BIAN::DataTypesLibrary::CoreDataTypes::ISO20022andUNCEFACT::Identifier  general-info: Reference to the parent Current Account Fulfillment Arrangement instance   # noqa: E501

        :return: The current_account_fulfillment_arrangement_instance_reference of this BQDepositsAndWithdrawalsExecuteInputModel.
        :rtype: str
        """
        return self._current_account_fulfillment_arrangement_instance_reference

    @current_account_fulfillment_arrangement_instance_reference.setter
    def current_account_fulfillment_arrangement_instance_reference(self, current_account_fulfillment_arrangement_instance_reference):
        """Sets the current_account_fulfillment_arrangement_instance_reference of this BQDepositsAndWithdrawalsExecuteInputModel.

        `status: Not Mapped`  core-data-type-reference: BIAN::DataTypesLibrary::CoreDataTypes::ISO20022andUNCEFACT::Identifier  general-info: Reference to the parent Current Account Fulfillment Arrangement instance   # noqa: E501

        :param current_account_fulfillment_arrangement_instance_reference: The current_account_fulfillment_arrangement_instance_reference of this BQDepositsAndWithdrawalsExecuteInputModel.
        :type current_account_fulfillment_arrangement_instance_reference: str
        """

        self._current_account_fulfillment_arrangement_instance_reference = current_account_fulfillment_arrangement_instance_reference

    @property
    def deposits_and_withdrawals_instance_reference(self):
        """Gets the deposits_and_withdrawals_instance_reference of this BQDepositsAndWithdrawalsExecuteInputModel.

        `status: Not Mapped`  core-data-type-reference: BIAN::DataTypesLibrary::CoreDataTypes::ISO20022andUNCEFACT::Identifier  general-info: Reference to the Deposits And Withdrawals instance   # noqa: E501

        :return: The deposits_and_withdrawals_instance_reference of this BQDepositsAndWithdrawalsExecuteInputModel.
        :rtype: str
        """
        return self._deposits_and_withdrawals_instance_reference

    @deposits_and_withdrawals_instance_reference.setter
    def deposits_and_withdrawals_instance_reference(self, deposits_and_withdrawals_instance_reference):
        """Sets the deposits_and_withdrawals_instance_reference of this BQDepositsAndWithdrawalsExecuteInputModel.

        `status: Not Mapped`  core-data-type-reference: BIAN::DataTypesLibrary::CoreDataTypes::ISO20022andUNCEFACT::Identifier  general-info: Reference to the Deposits And Withdrawals instance   # noqa: E501

        :param deposits_and_withdrawals_instance_reference: The deposits_and_withdrawals_instance_reference of this BQDepositsAndWithdrawalsExecuteInputModel.
        :type deposits_and_withdrawals_instance_reference: str
        """

        self._deposits_and_withdrawals_instance_reference = deposits_and_withdrawals_instance_reference

    @property
    def deposits_and_withdrawals_instance_record(self):
        """Gets the deposits_and_withdrawals_instance_record of this BQDepositsAndWithdrawalsExecuteInputModel.


        :return: The deposits_and_withdrawals_instance_record of this BQDepositsAndWithdrawalsExecuteInputModel.
        :rtype: CurrentAccountSdReferenceIdCurrentAccountFulfillmentArrangementCrReferenceIdDepositsandwithdrawalsBqReferenceIdExecutionDepositsAndWithdrawalsInstanceRecord
        """
        return self._deposits_and_withdrawals_instance_record

    @deposits_and_withdrawals_instance_record.setter
    def deposits_and_withdrawals_instance_record(self, deposits_and_withdrawals_instance_record):
        """Sets the deposits_and_withdrawals_instance_record of this BQDepositsAndWithdrawalsExecuteInputModel.


        :param deposits_and_withdrawals_instance_record: The deposits_and_withdrawals_instance_record of this BQDepositsAndWithdrawalsExecuteInputModel.
        :type deposits_and_withdrawals_instance_record: CurrentAccountSdReferenceIdCurrentAccountFulfillmentArrangementCrReferenceIdDepositsandwithdrawalsBqReferenceIdExecutionDepositsAndWithdrawalsInstanceRecord
        """

        self._deposits_and_withdrawals_instance_record = deposits_and_withdrawals_instance_record

    @property
    def deposits_and_withdrawals_execute_action_task_record(self):
        """Gets the deposits_and_withdrawals_execute_action_task_record of this BQDepositsAndWithdrawalsExecuteInputModel.

        `status: Not Mapped`  core-data-type-reference: BIAN::DataTypesLibrary::CoreDataTypes::UNCEFACT::Binary  general-info: The execute service call consolidated processing record   # noqa: E501

        :return: The deposits_and_withdrawals_execute_action_task_record of this BQDepositsAndWithdrawalsExecuteInputModel.
        :rtype: object
        """
        return self._deposits_and_withdrawals_execute_action_task_record

    @deposits_and_withdrawals_execute_action_task_record.setter
    def deposits_and_withdrawals_execute_action_task_record(self, deposits_and_withdrawals_execute_action_task_record):
        """Sets the deposits_and_withdrawals_execute_action_task_record of this BQDepositsAndWithdrawalsExecuteInputModel.

        `status: Not Mapped`  core-data-type-reference: BIAN::DataTypesLibrary::CoreDataTypes::UNCEFACT::Binary  general-info: The execute service call consolidated processing record   # noqa: E501

        :param deposits_and_withdrawals_execute_action_task_record: The deposits_and_withdrawals_execute_action_task_record of this BQDepositsAndWithdrawalsExecuteInputModel.
        :type deposits_and_withdrawals_execute_action_task_record: object
        """

        self._deposits_and_withdrawals_execute_action_task_record = deposits_and_withdrawals_execute_action_task_record

    @property
    def execute_record_type(self):
        """Gets the execute_record_type of this BQDepositsAndWithdrawalsExecuteInputModel.


        :return: The execute_record_type of this BQDepositsAndWithdrawalsExecuteInputModel.
        :rtype: CurrentAccountSdReferenceIdCurrentAccountFulfillmentArrangementCrReferenceIdServicefeesBqReferenceIdExecutionExecuteRecordType
        """
        return self._execute_record_type

    @execute_record_type.setter
    def execute_record_type(self, execute_record_type):
        """Sets the execute_record_type of this BQDepositsAndWithdrawalsExecuteInputModel.


        :param execute_record_type: The execute_record_type of this BQDepositsAndWithdrawalsExecuteInputModel.
        :type execute_record_type: CurrentAccountSdReferenceIdCurrentAccountFulfillmentArrangementCrReferenceIdServicefeesBqReferenceIdExecutionExecuteRecordType
        """

        self._execute_record_type = execute_record_type
