# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from tester.app.dto.base_model_ import Model
from tester import util




class BQDepositsAndWithdrawalsInitiateOutputModelCurrentAccountFulfillmentArrangementInstanceRecordPositionLimits(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, position_limit_value=None):  # noqa: E501
        """BQDepositsAndWithdrawalsInitiateOutputModelCurrentAccountFulfillmentArrangementInstanceRecordPositionLimits - a model defined in OpenAPI

        :param position_limit_value: The position_limit_value of this BQDepositsAndWithdrawalsInitiateOutputModelCurrentAccountFulfillmentArrangementInstanceRecordPositionLimits.  # noqa: E501
        :type position_limit_value: str
        """
        self.openapi_types = {
            'position_limit_value': str
        }

        self.attribute_map = {
            'position_limit_value': 'positionLimitValue'
        }

        self._position_limit_value = position_limit_value

    @classmethod
    def from_dict(cls, dikt) -> 'BQDepositsAndWithdrawalsInitiateOutputModelCurrentAccountFulfillmentArrangementInstanceRecordPositionLimits':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The BQDepositsAndWithdrawalsInitiateOutputModel_currentAccountFulfillmentArrangementInstanceRecord_positionLimits of this BQDepositsAndWithdrawalsInitiateOutputModelCurrentAccountFulfillmentArrangementInstanceRecordPositionLimits.  # noqa: E501
        :rtype: BQDepositsAndWithdrawalsInitiateOutputModelCurrentAccountFulfillmentArrangementInstanceRecordPositionLimits
        """
        return util.deserialize_model(dikt, cls)

    @property
    def position_limit_value(self):
        """Gets the position_limit_value of this BQDepositsAndWithdrawalsInitiateOutputModelCurrentAccountFulfillmentArrangementInstanceRecordPositionLimits.

        `status: Not Mapped`  core-data-type-reference: BIAN::DataTypesLibrary::CoreDataTypes::UNCEFACT::Text  general-info: The current calculated position   # noqa: E501

        :return: The position_limit_value of this BQDepositsAndWithdrawalsInitiateOutputModelCurrentAccountFulfillmentArrangementInstanceRecordPositionLimits.
        :rtype: str
        """
        return self._position_limit_value

    @position_limit_value.setter
    def position_limit_value(self, position_limit_value):
        """Sets the position_limit_value of this BQDepositsAndWithdrawalsInitiateOutputModelCurrentAccountFulfillmentArrangementInstanceRecordPositionLimits.

        `status: Not Mapped`  core-data-type-reference: BIAN::DataTypesLibrary::CoreDataTypes::UNCEFACT::Text  general-info: The current calculated position   # noqa: E501

        :param position_limit_value: The position_limit_value of this BQDepositsAndWithdrawalsInitiateOutputModelCurrentAccountFulfillmentArrangementInstanceRecordPositionLimits.
        :type position_limit_value: str
        """

        self._position_limit_value = position_limit_value
