# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from tester.app.dto.base_model_ import Model
from tester.app.dto.inline_response20016_deposits_and_withdrawals_instance_record_deposit_transaction import InlineResponse20016DepositsAndWithdrawalsInstanceRecordDepositTransaction
from tester.app.dto.inline_response20016_deposits_and_withdrawals_instance_record_withdrawal_transaction import InlineResponse20016DepositsAndWithdrawalsInstanceRecordWithdrawalTransaction
from tester import util

from tester.app.dto.inline_response20016_deposits_and_withdrawals_instance_record_deposit_transaction import InlineResponse20016DepositsAndWithdrawalsInstanceRecordDepositTransaction  # noqa: E501
from tester.app.dto.inline_response20016_deposits_and_withdrawals_instance_record_withdrawal_transaction import InlineResponse20016DepositsAndWithdrawalsInstanceRecordWithdrawalTransaction  # noqa: E501



class BQDepositsAndWithdrawalsExecuteOutputModelDepositsAndWithdrawalsInstanceRecord(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, deposit_transaction=None, withdrawal_transaction=None):  # noqa: E501
        """BQDepositsAndWithdrawalsExecuteOutputModelDepositsAndWithdrawalsInstanceRecord - a model defined in OpenAPI

        :param deposit_transaction: The deposit_transaction of this BQDepositsAndWithdrawalsExecuteOutputModelDepositsAndWithdrawalsInstanceRecord.  # noqa: E501
        :type deposit_transaction: InlineResponse20016DepositsAndWithdrawalsInstanceRecordDepositTransaction
        :param withdrawal_transaction: The withdrawal_transaction of this BQDepositsAndWithdrawalsExecuteOutputModelDepositsAndWithdrawalsInstanceRecord.  # noqa: E501
        :type withdrawal_transaction: InlineResponse20016DepositsAndWithdrawalsInstanceRecordWithdrawalTransaction
        """
        self.openapi_types = {
            'deposit_transaction': InlineResponse20016DepositsAndWithdrawalsInstanceRecordDepositTransaction,
            'withdrawal_transaction': InlineResponse20016DepositsAndWithdrawalsInstanceRecordWithdrawalTransaction
        }

        self.attribute_map = {
            'deposit_transaction': 'depositTransaction',
            'withdrawal_transaction': 'withdrawalTransaction'
        }

        self._deposit_transaction = deposit_transaction
        self._withdrawal_transaction = withdrawal_transaction

    @classmethod
    def from_dict(cls, dikt) -> 'BQDepositsAndWithdrawalsExecuteOutputModelDepositsAndWithdrawalsInstanceRecord':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The BQDepositsAndWithdrawalsExecuteOutputModel_depositsAndWithdrawalsInstanceRecord of this BQDepositsAndWithdrawalsExecuteOutputModelDepositsAndWithdrawalsInstanceRecord.  # noqa: E501
        :rtype: BQDepositsAndWithdrawalsExecuteOutputModelDepositsAndWithdrawalsInstanceRecord
        """
        return util.deserialize_model(dikt, cls)

    @property
    def deposit_transaction(self):
        """Gets the deposit_transaction of this BQDepositsAndWithdrawalsExecuteOutputModelDepositsAndWithdrawalsInstanceRecord.


        :return: The deposit_transaction of this BQDepositsAndWithdrawalsExecuteOutputModelDepositsAndWithdrawalsInstanceRecord.
        :rtype: InlineResponse20016DepositsAndWithdrawalsInstanceRecordDepositTransaction
        """
        return self._deposit_transaction

    @deposit_transaction.setter
    def deposit_transaction(self, deposit_transaction):
        """Sets the deposit_transaction of this BQDepositsAndWithdrawalsExecuteOutputModelDepositsAndWithdrawalsInstanceRecord.


        :param deposit_transaction: The deposit_transaction of this BQDepositsAndWithdrawalsExecuteOutputModelDepositsAndWithdrawalsInstanceRecord.
        :type deposit_transaction: InlineResponse20016DepositsAndWithdrawalsInstanceRecordDepositTransaction
        """

        self._deposit_transaction = deposit_transaction

    @property
    def withdrawal_transaction(self):
        """Gets the withdrawal_transaction of this BQDepositsAndWithdrawalsExecuteOutputModelDepositsAndWithdrawalsInstanceRecord.


        :return: The withdrawal_transaction of this BQDepositsAndWithdrawalsExecuteOutputModelDepositsAndWithdrawalsInstanceRecord.
        :rtype: InlineResponse20016DepositsAndWithdrawalsInstanceRecordWithdrawalTransaction
        """
        return self._withdrawal_transaction

    @withdrawal_transaction.setter
    def withdrawal_transaction(self, withdrawal_transaction):
        """Sets the withdrawal_transaction of this BQDepositsAndWithdrawalsExecuteOutputModelDepositsAndWithdrawalsInstanceRecord.


        :param withdrawal_transaction: The withdrawal_transaction of this BQDepositsAndWithdrawalsExecuteOutputModelDepositsAndWithdrawalsInstanceRecord.
        :type withdrawal_transaction: InlineResponse20016DepositsAndWithdrawalsInstanceRecordWithdrawalTransaction
        """

        self._withdrawal_transaction = withdrawal_transaction
