# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from tester.app.dto.base_model_ import Model
from tester.app.dto.bq_interest_retrieve_input_model_interest_instance_analysis1 import BQInterestRetrieveInputModelInterestInstanceAnalysis1
from tester.app.dto.bq_interest_retrieve_input_model_interest_instance_report1 import BQInterestRetrieveInputModelInterestInstanceReport1
from tester import util

from tester.app.dto.bq_interest_retrieve_input_model_interest_instance_analysis1 import BQInterestRetrieveInputModelInterestInstanceAnalysis1  # noqa: E501
from tester.app.dto.bq_interest_retrieve_input_model_interest_instance_report1 import BQInterestRetrieveInputModelInterestInstanceReport1  # noqa: E501



class BQInterestRetrieveInputModel(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, interest_retrieve_action_task_record=None, interest_retrieve_action_request=None, interest_instance_report=None, interest_instance_analysis=None):  # noqa: E501
        """BQInterestRetrieveInputModel - a model defined in OpenAPI

        :param interest_retrieve_action_task_record: The interest_retrieve_action_task_record of this BQInterestRetrieveInputModel.  # noqa: E501
        :type interest_retrieve_action_task_record: object
        :param interest_retrieve_action_request: The interest_retrieve_action_request of this BQInterestRetrieveInputModel.  # noqa: E501
        :type interest_retrieve_action_request: str
        :param interest_instance_report: The interest_instance_report of this BQInterestRetrieveInputModel.  # noqa: E501
        :type interest_instance_report: BQInterestRetrieveInputModelInterestInstanceReport1
        :param interest_instance_analysis: The interest_instance_analysis of this BQInterestRetrieveInputModel.  # noqa: E501
        :type interest_instance_analysis: BQInterestRetrieveInputModelInterestInstanceAnalysis1
        """
        self.openapi_types = {
            'interest_retrieve_action_task_record': object,
            'interest_retrieve_action_request': str,
            'interest_instance_report': BQInterestRetrieveInputModelInterestInstanceReport1,
            'interest_instance_analysis': BQInterestRetrieveInputModelInterestInstanceAnalysis1
        }

        self.attribute_map = {
            'interest_retrieve_action_task_record': 'interestRetrieveActionTaskRecord',
            'interest_retrieve_action_request': 'interestRetrieveActionRequest',
            'interest_instance_report': 'interestInstanceReport',
            'interest_instance_analysis': 'interestInstanceAnalysis'
        }

        self._interest_retrieve_action_task_record = interest_retrieve_action_task_record
        self._interest_retrieve_action_request = interest_retrieve_action_request
        self._interest_instance_report = interest_instance_report
        self._interest_instance_analysis = interest_instance_analysis

    @classmethod
    def from_dict(cls, dikt) -> 'BQInterestRetrieveInputModel':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The BQInterestRetrieveInputModel of this BQInterestRetrieveInputModel.  # noqa: E501
        :rtype: BQInterestRetrieveInputModel
        """
        return util.deserialize_model(dikt, cls)

    @property
    def interest_retrieve_action_task_record(self):
        """Gets the interest_retrieve_action_task_record of this BQInterestRetrieveInputModel.

        `status: Not Mapped`  core-data-type-reference: BIAN::DataTypesLibrary::CoreDataTypes::UNCEFACT::Binary  general-info: The retrieve service call consolidated processing record   # noqa: E501

        :return: The interest_retrieve_action_task_record of this BQInterestRetrieveInputModel.
        :rtype: object
        """
        return self._interest_retrieve_action_task_record

    @interest_retrieve_action_task_record.setter
    def interest_retrieve_action_task_record(self, interest_retrieve_action_task_record):
        """Sets the interest_retrieve_action_task_record of this BQInterestRetrieveInputModel.

        `status: Not Mapped`  core-data-type-reference: BIAN::DataTypesLibrary::CoreDataTypes::UNCEFACT::Binary  general-info: The retrieve service call consolidated processing record   # noqa: E501

        :param interest_retrieve_action_task_record: The interest_retrieve_action_task_record of this BQInterestRetrieveInputModel.
        :type interest_retrieve_action_task_record: object
        """

        self._interest_retrieve_action_task_record = interest_retrieve_action_task_record

    @property
    def interest_retrieve_action_request(self):
        """Gets the interest_retrieve_action_request of this BQInterestRetrieveInputModel.

        `status: Not Mapped`  core-data-type-reference: BIAN::DataTypesLibrary::CoreDataTypes::UNCEFACT::Text  general-info: Details of the retrieve action service request (lists requested reports)   # noqa: E501

        :return: The interest_retrieve_action_request of this BQInterestRetrieveInputModel.
        :rtype: str
        """
        return self._interest_retrieve_action_request

    @interest_retrieve_action_request.setter
    def interest_retrieve_action_request(self, interest_retrieve_action_request):
        """Sets the interest_retrieve_action_request of this BQInterestRetrieveInputModel.

        `status: Not Mapped`  core-data-type-reference: BIAN::DataTypesLibrary::CoreDataTypes::UNCEFACT::Text  general-info: Details of the retrieve action service request (lists requested reports)   # noqa: E501

        :param interest_retrieve_action_request: The interest_retrieve_action_request of this BQInterestRetrieveInputModel.
        :type interest_retrieve_action_request: str
        """

        self._interest_retrieve_action_request = interest_retrieve_action_request

    @property
    def interest_instance_report(self):
        """Gets the interest_instance_report of this BQInterestRetrieveInputModel.


        :return: The interest_instance_report of this BQInterestRetrieveInputModel.
        :rtype: BQInterestRetrieveInputModelInterestInstanceReport1
        """
        return self._interest_instance_report

    @interest_instance_report.setter
    def interest_instance_report(self, interest_instance_report):
        """Sets the interest_instance_report of this BQInterestRetrieveInputModel.


        :param interest_instance_report: The interest_instance_report of this BQInterestRetrieveInputModel.
        :type interest_instance_report: BQInterestRetrieveInputModelInterestInstanceReport1
        """

        self._interest_instance_report = interest_instance_report

    @property
    def interest_instance_analysis(self):
        """Gets the interest_instance_analysis of this BQInterestRetrieveInputModel.


        :return: The interest_instance_analysis of this BQInterestRetrieveInputModel.
        :rtype: BQInterestRetrieveInputModelInterestInstanceAnalysis1
        """
        return self._interest_instance_analysis

    @interest_instance_analysis.setter
    def interest_instance_analysis(self, interest_instance_analysis):
        """Sets the interest_instance_analysis of this BQInterestRetrieveInputModel.


        :param interest_instance_analysis: The interest_instance_analysis of this BQInterestRetrieveInputModel.
        :type interest_instance_analysis: BQInterestRetrieveInputModelInterestInstanceAnalysis1
        """

        self._interest_instance_analysis = interest_instance_analysis
