# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from tester.app.dto.base_model_ import Model
from tester import util




class BQInterestRetrieveOutputModelInterestInstanceReport(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, interest_instance_report_record=None, interest_instance_report_type=None, interest_instance_report_parameters=None, interest_instance_report=None):  # noqa: E501
        """BQInterestRetrieveOutputModelInterestInstanceReport - a model defined in OpenAPI

        :param interest_instance_report_record: The interest_instance_report_record of this BQInterestRetrieveOutputModelInterestInstanceReport.  # noqa: E501
        :type interest_instance_report_record: object
        :param interest_instance_report_type: The interest_instance_report_type of this BQInterestRetrieveOutputModelInterestInstanceReport.  # noqa: E501
        :type interest_instance_report_type: str
        :param interest_instance_report_parameters: The interest_instance_report_parameters of this BQInterestRetrieveOutputModelInterestInstanceReport.  # noqa: E501
        :type interest_instance_report_parameters: str
        :param interest_instance_report: The interest_instance_report of this BQInterestRetrieveOutputModelInterestInstanceReport.  # noqa: E501
        :type interest_instance_report: object
        """
        self.openapi_types = {
            'interest_instance_report_record': object,
            'interest_instance_report_type': str,
            'interest_instance_report_parameters': str,
            'interest_instance_report': object
        }

        self.attribute_map = {
            'interest_instance_report_record': 'interestInstanceReportRecord',
            'interest_instance_report_type': 'interestInstanceReportType',
            'interest_instance_report_parameters': 'interestInstanceReportParameters',
            'interest_instance_report': 'interestInstanceReport'
        }

        self._interest_instance_report_record = interest_instance_report_record
        self._interest_instance_report_type = interest_instance_report_type
        self._interest_instance_report_parameters = interest_instance_report_parameters
        self._interest_instance_report = interest_instance_report

    @classmethod
    def from_dict(cls, dikt) -> 'BQInterestRetrieveOutputModelInterestInstanceReport':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The BQInterestRetrieveOutputModel_interestInstanceReport of this BQInterestRetrieveOutputModelInterestInstanceReport.  # noqa: E501
        :rtype: BQInterestRetrieveOutputModelInterestInstanceReport
        """
        return util.deserialize_model(dikt, cls)

    @property
    def interest_instance_report_record(self):
        """Gets the interest_instance_report_record of this BQInterestRetrieveOutputModelInterestInstanceReport.

        `status: Not Mapped`  core-data-type-reference: BIAN::DataTypesLibrary::CoreDataTypes::UNCEFACT::Binary  general-info: The input information used to assemble the report that can be on-going, periodic and actual and projected   # noqa: E501

        :return: The interest_instance_report_record of this BQInterestRetrieveOutputModelInterestInstanceReport.
        :rtype: object
        """
        return self._interest_instance_report_record

    @interest_instance_report_record.setter
    def interest_instance_report_record(self, interest_instance_report_record):
        """Sets the interest_instance_report_record of this BQInterestRetrieveOutputModelInterestInstanceReport.

        `status: Not Mapped`  core-data-type-reference: BIAN::DataTypesLibrary::CoreDataTypes::UNCEFACT::Binary  general-info: The input information used to assemble the report that can be on-going, periodic and actual and projected   # noqa: E501

        :param interest_instance_report_record: The interest_instance_report_record of this BQInterestRetrieveOutputModelInterestInstanceReport.
        :type interest_instance_report_record: object
        """

        self._interest_instance_report_record = interest_instance_report_record

    @property
    def interest_instance_report_type(self):
        """Gets the interest_instance_report_type of this BQInterestRetrieveOutputModelInterestInstanceReport.

        `status: Not Mapped`  core-data-type-reference: BIAN::DataTypesLibrary::CoreDataTypes::UNCEFACT::Code  general-info: The type of external report available   # noqa: E501

        :return: The interest_instance_report_type of this BQInterestRetrieveOutputModelInterestInstanceReport.
        :rtype: str
        """
        return self._interest_instance_report_type

    @interest_instance_report_type.setter
    def interest_instance_report_type(self, interest_instance_report_type):
        """Sets the interest_instance_report_type of this BQInterestRetrieveOutputModelInterestInstanceReport.

        `status: Not Mapped`  core-data-type-reference: BIAN::DataTypesLibrary::CoreDataTypes::UNCEFACT::Code  general-info: The type of external report available   # noqa: E501

        :param interest_instance_report_type: The interest_instance_report_type of this BQInterestRetrieveOutputModelInterestInstanceReport.
        :type interest_instance_report_type: str
        """

        self._interest_instance_report_type = interest_instance_report_type

    @property
    def interest_instance_report_parameters(self):
        """Gets the interest_instance_report_parameters of this BQInterestRetrieveOutputModelInterestInstanceReport.

        `status: Not Mapped`  core-data-type-reference: BIAN::DataTypesLibrary::CoreDataTypes::UNCEFACT::Text  general-info: The selection parameters for the report (e.g. period, content type)   # noqa: E501

        :return: The interest_instance_report_parameters of this BQInterestRetrieveOutputModelInterestInstanceReport.
        :rtype: str
        """
        return self._interest_instance_report_parameters

    @interest_instance_report_parameters.setter
    def interest_instance_report_parameters(self, interest_instance_report_parameters):
        """Sets the interest_instance_report_parameters of this BQInterestRetrieveOutputModelInterestInstanceReport.

        `status: Not Mapped`  core-data-type-reference: BIAN::DataTypesLibrary::CoreDataTypes::UNCEFACT::Text  general-info: The selection parameters for the report (e.g. period, content type)   # noqa: E501

        :param interest_instance_report_parameters: The interest_instance_report_parameters of this BQInterestRetrieveOutputModelInterestInstanceReport.
        :type interest_instance_report_parameters: str
        """

        self._interest_instance_report_parameters = interest_instance_report_parameters

    @property
    def interest_instance_report(self):
        """Gets the interest_instance_report of this BQInterestRetrieveOutputModelInterestInstanceReport.

        `status: Not Mapped`  core-data-type-reference: BIAN::DataTypesLibrary::CoreDataTypes::UNCEFACT::Binary  general-info: The external report in any suitable form including selection filters where appropriate   # noqa: E501

        :return: The interest_instance_report of this BQInterestRetrieveOutputModelInterestInstanceReport.
        :rtype: object
        """
        return self._interest_instance_report

    @interest_instance_report.setter
    def interest_instance_report(self, interest_instance_report):
        """Sets the interest_instance_report of this BQInterestRetrieveOutputModelInterestInstanceReport.

        `status: Not Mapped`  core-data-type-reference: BIAN::DataTypesLibrary::CoreDataTypes::UNCEFACT::Binary  general-info: The external report in any suitable form including selection filters where appropriate   # noqa: E501

        :param interest_instance_report: The interest_instance_report of this BQInterestRetrieveOutputModelInterestInstanceReport.
        :type interest_instance_report: object
        """

        self._interest_instance_report = interest_instance_report
