# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from tester.app.dto.base_model_ import Model
from tester import util




class BQIssuedDeviceRetrieveOutputModelIssuedDeviceInstanceReport(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, issued_device_instance_report_record=None, issued_device_instance_report_type=None, issued_device_instance_report_parameters=None, issued_device_instance_report=None):  # noqa: E501
        """BQIssuedDeviceRetrieveOutputModelIssuedDeviceInstanceReport - a model defined in OpenAPI

        :param issued_device_instance_report_record: The issued_device_instance_report_record of this BQIssuedDeviceRetrieveOutputModelIssuedDeviceInstanceReport.  # noqa: E501
        :type issued_device_instance_report_record: object
        :param issued_device_instance_report_type: The issued_device_instance_report_type of this BQIssuedDeviceRetrieveOutputModelIssuedDeviceInstanceReport.  # noqa: E501
        :type issued_device_instance_report_type: str
        :param issued_device_instance_report_parameters: The issued_device_instance_report_parameters of this BQIssuedDeviceRetrieveOutputModelIssuedDeviceInstanceReport.  # noqa: E501
        :type issued_device_instance_report_parameters: str
        :param issued_device_instance_report: The issued_device_instance_report of this BQIssuedDeviceRetrieveOutputModelIssuedDeviceInstanceReport.  # noqa: E501
        :type issued_device_instance_report: object
        """
        self.openapi_types = {
            'issued_device_instance_report_record': object,
            'issued_device_instance_report_type': str,
            'issued_device_instance_report_parameters': str,
            'issued_device_instance_report': object
        }

        self.attribute_map = {
            'issued_device_instance_report_record': 'issuedDeviceInstanceReportRecord',
            'issued_device_instance_report_type': 'issuedDeviceInstanceReportType',
            'issued_device_instance_report_parameters': 'issuedDeviceInstanceReportParameters',
            'issued_device_instance_report': 'issuedDeviceInstanceReport'
        }

        self._issued_device_instance_report_record = issued_device_instance_report_record
        self._issued_device_instance_report_type = issued_device_instance_report_type
        self._issued_device_instance_report_parameters = issued_device_instance_report_parameters
        self._issued_device_instance_report = issued_device_instance_report

    @classmethod
    def from_dict(cls, dikt) -> 'BQIssuedDeviceRetrieveOutputModelIssuedDeviceInstanceReport':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The BQIssuedDeviceRetrieveOutputModel_issuedDeviceInstanceReport of this BQIssuedDeviceRetrieveOutputModelIssuedDeviceInstanceReport.  # noqa: E501
        :rtype: BQIssuedDeviceRetrieveOutputModelIssuedDeviceInstanceReport
        """
        return util.deserialize_model(dikt, cls)

    @property
    def issued_device_instance_report_record(self):
        """Gets the issued_device_instance_report_record of this BQIssuedDeviceRetrieveOutputModelIssuedDeviceInstanceReport.

        `status: Not Mapped`  core-data-type-reference: BIAN::DataTypesLibrary::CoreDataTypes::UNCEFACT::Binary  general-info: The input information used to assemble the report that can be on-going, periodic and actual and projected   # noqa: E501

        :return: The issued_device_instance_report_record of this BQIssuedDeviceRetrieveOutputModelIssuedDeviceInstanceReport.
        :rtype: object
        """
        return self._issued_device_instance_report_record

    @issued_device_instance_report_record.setter
    def issued_device_instance_report_record(self, issued_device_instance_report_record):
        """Sets the issued_device_instance_report_record of this BQIssuedDeviceRetrieveOutputModelIssuedDeviceInstanceReport.

        `status: Not Mapped`  core-data-type-reference: BIAN::DataTypesLibrary::CoreDataTypes::UNCEFACT::Binary  general-info: The input information used to assemble the report that can be on-going, periodic and actual and projected   # noqa: E501

        :param issued_device_instance_report_record: The issued_device_instance_report_record of this BQIssuedDeviceRetrieveOutputModelIssuedDeviceInstanceReport.
        :type issued_device_instance_report_record: object
        """

        self._issued_device_instance_report_record = issued_device_instance_report_record

    @property
    def issued_device_instance_report_type(self):
        """Gets the issued_device_instance_report_type of this BQIssuedDeviceRetrieveOutputModelIssuedDeviceInstanceReport.

        `status: Not Mapped`  core-data-type-reference: BIAN::DataTypesLibrary::CoreDataTypes::UNCEFACT::Code  general-info: The type of external report available   # noqa: E501

        :return: The issued_device_instance_report_type of this BQIssuedDeviceRetrieveOutputModelIssuedDeviceInstanceReport.
        :rtype: str
        """
        return self._issued_device_instance_report_type

    @issued_device_instance_report_type.setter
    def issued_device_instance_report_type(self, issued_device_instance_report_type):
        """Sets the issued_device_instance_report_type of this BQIssuedDeviceRetrieveOutputModelIssuedDeviceInstanceReport.

        `status: Not Mapped`  core-data-type-reference: BIAN::DataTypesLibrary::CoreDataTypes::UNCEFACT::Code  general-info: The type of external report available   # noqa: E501

        :param issued_device_instance_report_type: The issued_device_instance_report_type of this BQIssuedDeviceRetrieveOutputModelIssuedDeviceInstanceReport.
        :type issued_device_instance_report_type: str
        """

        self._issued_device_instance_report_type = issued_device_instance_report_type

    @property
    def issued_device_instance_report_parameters(self):
        """Gets the issued_device_instance_report_parameters of this BQIssuedDeviceRetrieveOutputModelIssuedDeviceInstanceReport.

        `status: Not Mapped`  core-data-type-reference: BIAN::DataTypesLibrary::CoreDataTypes::UNCEFACT::Text  general-info: The selection parameters for the report (e.g. period, content type)   # noqa: E501

        :return: The issued_device_instance_report_parameters of this BQIssuedDeviceRetrieveOutputModelIssuedDeviceInstanceReport.
        :rtype: str
        """
        return self._issued_device_instance_report_parameters

    @issued_device_instance_report_parameters.setter
    def issued_device_instance_report_parameters(self, issued_device_instance_report_parameters):
        """Sets the issued_device_instance_report_parameters of this BQIssuedDeviceRetrieveOutputModelIssuedDeviceInstanceReport.

        `status: Not Mapped`  core-data-type-reference: BIAN::DataTypesLibrary::CoreDataTypes::UNCEFACT::Text  general-info: The selection parameters for the report (e.g. period, content type)   # noqa: E501

        :param issued_device_instance_report_parameters: The issued_device_instance_report_parameters of this BQIssuedDeviceRetrieveOutputModelIssuedDeviceInstanceReport.
        :type issued_device_instance_report_parameters: str
        """

        self._issued_device_instance_report_parameters = issued_device_instance_report_parameters

    @property
    def issued_device_instance_report(self):
        """Gets the issued_device_instance_report of this BQIssuedDeviceRetrieveOutputModelIssuedDeviceInstanceReport.

        `status: Not Mapped`  core-data-type-reference: BIAN::DataTypesLibrary::CoreDataTypes::UNCEFACT::Binary  general-info: The external report in any suitable form including selection filters where appropriate   # noqa: E501

        :return: The issued_device_instance_report of this BQIssuedDeviceRetrieveOutputModelIssuedDeviceInstanceReport.
        :rtype: object
        """
        return self._issued_device_instance_report

    @issued_device_instance_report.setter
    def issued_device_instance_report(self, issued_device_instance_report):
        """Sets the issued_device_instance_report of this BQIssuedDeviceRetrieveOutputModelIssuedDeviceInstanceReport.

        `status: Not Mapped`  core-data-type-reference: BIAN::DataTypesLibrary::CoreDataTypes::UNCEFACT::Binary  general-info: The external report in any suitable form including selection filters where appropriate   # noqa: E501

        :param issued_device_instance_report: The issued_device_instance_report of this BQIssuedDeviceRetrieveOutputModelIssuedDeviceInstanceReport.
        :type issued_device_instance_report: object
        """

        self._issued_device_instance_report = issued_device_instance_report
