# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from tester.app.dto.base_model_ import Model
from tester import util




class BQPaymentsInitiateOutputModelCurrentAccountFulfillmentArrangementInstanceRecordAssociations(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, association_type=None, association_obligation_entitlement=None, association_reference=None):  # noqa: E501
        """BQPaymentsInitiateOutputModelCurrentAccountFulfillmentArrangementInstanceRecordAssociations - a model defined in OpenAPI

        :param association_type: The association_type of this BQPaymentsInitiateOutputModelCurrentAccountFulfillmentArrangementInstanceRecordAssociations.  # noqa: E501
        :type association_type: str
        :param association_obligation_entitlement: The association_obligation_entitlement of this BQPaymentsInitiateOutputModelCurrentAccountFulfillmentArrangementInstanceRecordAssociations.  # noqa: E501
        :type association_obligation_entitlement: str
        :param association_reference: The association_reference of this BQPaymentsInitiateOutputModelCurrentAccountFulfillmentArrangementInstanceRecordAssociations.  # noqa: E501
        :type association_reference: str
        """
        self.openapi_types = {
            'association_type': str,
            'association_obligation_entitlement': str,
            'association_reference': str
        }

        self.attribute_map = {
            'association_type': 'associationType',
            'association_obligation_entitlement': 'associationObligationEntitlement',
            'association_reference': 'associationReference'
        }

        self._association_type = association_type
        self._association_obligation_entitlement = association_obligation_entitlement
        self._association_reference = association_reference

    @classmethod
    def from_dict(cls, dikt) -> 'BQPaymentsInitiateOutputModelCurrentAccountFulfillmentArrangementInstanceRecordAssociations':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The BQPaymentsInitiateOutputModel_currentAccountFulfillmentArrangementInstanceRecord_associations of this BQPaymentsInitiateOutputModelCurrentAccountFulfillmentArrangementInstanceRecordAssociations.  # noqa: E501
        :rtype: BQPaymentsInitiateOutputModelCurrentAccountFulfillmentArrangementInstanceRecordAssociations
        """
        return util.deserialize_model(dikt, cls)

    @property
    def association_type(self):
        """Gets the association_type of this BQPaymentsInitiateOutputModelCurrentAccountFulfillmentArrangementInstanceRecordAssociations.

        general-info: The type of association (e.g. guarantor, co-signer)   # noqa: E501

        :return: The association_type of this BQPaymentsInitiateOutputModelCurrentAccountFulfillmentArrangementInstanceRecordAssociations.
        :rtype: str
        """
        return self._association_type

    @association_type.setter
    def association_type(self, association_type):
        """Sets the association_type of this BQPaymentsInitiateOutputModelCurrentAccountFulfillmentArrangementInstanceRecordAssociations.

        general-info: The type of association (e.g. guarantor, co-signer)   # noqa: E501

        :param association_type: The association_type of this BQPaymentsInitiateOutputModelCurrentAccountFulfillmentArrangementInstanceRecordAssociations.
        :type association_type: str
        """

        self._association_type = association_type

    @property
    def association_obligation_entitlement(self):
        """Gets the association_obligation_entitlement of this BQPaymentsInitiateOutputModelCurrentAccountFulfillmentArrangementInstanceRecordAssociations.

        `status: Not Mapped`  core-data-type-reference: BIAN::DataTypesLibrary::CoreDataTypes::UNCEFACT::Text  general-info: Description of the role, obligations or entitlements of the associated party   # noqa: E501

        :return: The association_obligation_entitlement of this BQPaymentsInitiateOutputModelCurrentAccountFulfillmentArrangementInstanceRecordAssociations.
        :rtype: str
        """
        return self._association_obligation_entitlement

    @association_obligation_entitlement.setter
    def association_obligation_entitlement(self, association_obligation_entitlement):
        """Sets the association_obligation_entitlement of this BQPaymentsInitiateOutputModelCurrentAccountFulfillmentArrangementInstanceRecordAssociations.

        `status: Not Mapped`  core-data-type-reference: BIAN::DataTypesLibrary::CoreDataTypes::UNCEFACT::Text  general-info: Description of the role, obligations or entitlements of the associated party   # noqa: E501

        :param association_obligation_entitlement: The association_obligation_entitlement of this BQPaymentsInitiateOutputModelCurrentAccountFulfillmentArrangementInstanceRecordAssociations.
        :type association_obligation_entitlement: str
        """

        self._association_obligation_entitlement = association_obligation_entitlement

    @property
    def association_reference(self):
        """Gets the association_reference of this BQPaymentsInitiateOutputModelCurrentAccountFulfillmentArrangementInstanceRecordAssociations.

        `status: Registered`  iso-link: https://www.iso20022.org/standardsrepository/public/wqt/Description/mx/dico/bc/_E1rHgsTGEeChad0JzLk7QA_-1068889728/elements/_E10RccTGEeChad0JzLk7QA_1392095805  bian-reference: CurrentAccountAgreement (as Agreement).AgreementInvolvement  general-info: Reference to the associated party   # noqa: E501

        :return: The association_reference of this BQPaymentsInitiateOutputModelCurrentAccountFulfillmentArrangementInstanceRecordAssociations.
        :rtype: str
        """
        return self._association_reference

    @association_reference.setter
    def association_reference(self, association_reference):
        """Sets the association_reference of this BQPaymentsInitiateOutputModelCurrentAccountFulfillmentArrangementInstanceRecordAssociations.

        `status: Registered`  iso-link: https://www.iso20022.org/standardsrepository/public/wqt/Description/mx/dico/bc/_E1rHgsTGEeChad0JzLk7QA_-1068889728/elements/_E10RccTGEeChad0JzLk7QA_1392095805  bian-reference: CurrentAccountAgreement (as Agreement).AgreementInvolvement  general-info: Reference to the associated party   # noqa: E501

        :param association_reference: The association_reference of this BQPaymentsInitiateOutputModelCurrentAccountFulfillmentArrangementInstanceRecordAssociations.
        :type association_reference: str
        """

        self._association_reference = association_reference
