# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from tester.app.dto.base_model_ import Model
from tester import util




class BQPaymentsExchangeOutputModel(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, payments_exchange_action_task_reference=None, payments_exchange_action_task_record=None, payments_exchange_action_response=None, payments_instance_status=None):  # noqa: E501
        """BQPaymentsExchangeOutputModel - a model defined in OpenAPI

        :param payments_exchange_action_task_reference: The payments_exchange_action_task_reference of this BQPaymentsExchangeOutputModel.  # noqa: E501
        :type payments_exchange_action_task_reference: str
        :param payments_exchange_action_task_record: The payments_exchange_action_task_record of this BQPaymentsExchangeOutputModel.  # noqa: E501
        :type payments_exchange_action_task_record: object
        :param payments_exchange_action_response: The payments_exchange_action_response of this BQPaymentsExchangeOutputModel.  # noqa: E501
        :type payments_exchange_action_response: str
        :param payments_instance_status: The payments_instance_status of this BQPaymentsExchangeOutputModel.  # noqa: E501
        :type payments_instance_status: str
        """
        self.openapi_types = {
            'payments_exchange_action_task_reference': str,
            'payments_exchange_action_task_record': object,
            'payments_exchange_action_response': str,
            'payments_instance_status': str
        }

        self.attribute_map = {
            'payments_exchange_action_task_reference': 'paymentsExchangeActionTaskReference',
            'payments_exchange_action_task_record': 'paymentsExchangeActionTaskRecord',
            'payments_exchange_action_response': 'paymentsExchangeActionResponse',
            'payments_instance_status': 'paymentsInstanceStatus'
        }

        self._payments_exchange_action_task_reference = payments_exchange_action_task_reference
        self._payments_exchange_action_task_record = payments_exchange_action_task_record
        self._payments_exchange_action_response = payments_exchange_action_response
        self._payments_instance_status = payments_instance_status

    @classmethod
    def from_dict(cls, dikt) -> 'BQPaymentsExchangeOutputModel':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The BQPaymentsExchangeOutputModel of this BQPaymentsExchangeOutputModel.  # noqa: E501
        :rtype: BQPaymentsExchangeOutputModel
        """
        return util.deserialize_model(dikt, cls)

    @property
    def payments_exchange_action_task_reference(self):
        """Gets the payments_exchange_action_task_reference of this BQPaymentsExchangeOutputModel.

        `status: Not Mapped`  core-data-type-reference: BIAN::DataTypesLibrary::CoreDataTypes::ISO20022andUNCEFACT::Identifier  general-info: Reference to a Payments instance exchange service call   # noqa: E501

        :return: The payments_exchange_action_task_reference of this BQPaymentsExchangeOutputModel.
        :rtype: str
        """
        return self._payments_exchange_action_task_reference

    @payments_exchange_action_task_reference.setter
    def payments_exchange_action_task_reference(self, payments_exchange_action_task_reference):
        """Sets the payments_exchange_action_task_reference of this BQPaymentsExchangeOutputModel.

        `status: Not Mapped`  core-data-type-reference: BIAN::DataTypesLibrary::CoreDataTypes::ISO20022andUNCEFACT::Identifier  general-info: Reference to a Payments instance exchange service call   # noqa: E501

        :param payments_exchange_action_task_reference: The payments_exchange_action_task_reference of this BQPaymentsExchangeOutputModel.
        :type payments_exchange_action_task_reference: str
        """

        self._payments_exchange_action_task_reference = payments_exchange_action_task_reference

    @property
    def payments_exchange_action_task_record(self):
        """Gets the payments_exchange_action_task_record of this BQPaymentsExchangeOutputModel.

        `status: Not Mapped`  core-data-type-reference: BIAN::DataTypesLibrary::CoreDataTypes::UNCEFACT::Binary  general-info: The exchange service call consolidated processing record   # noqa: E501

        :return: The payments_exchange_action_task_record of this BQPaymentsExchangeOutputModel.
        :rtype: object
        """
        return self._payments_exchange_action_task_record

    @payments_exchange_action_task_record.setter
    def payments_exchange_action_task_record(self, payments_exchange_action_task_record):
        """Sets the payments_exchange_action_task_record of this BQPaymentsExchangeOutputModel.

        `status: Not Mapped`  core-data-type-reference: BIAN::DataTypesLibrary::CoreDataTypes::UNCEFACT::Binary  general-info: The exchange service call consolidated processing record   # noqa: E501

        :param payments_exchange_action_task_record: The payments_exchange_action_task_record of this BQPaymentsExchangeOutputModel.
        :type payments_exchange_action_task_record: object
        """

        self._payments_exchange_action_task_record = payments_exchange_action_task_record

    @property
    def payments_exchange_action_response(self):
        """Gets the payments_exchange_action_response of this BQPaymentsExchangeOutputModel.

        `status: Not Mapped`  core-data-type-reference: BIAN::DataTypesLibrary::CoreDataTypes::UNCEFACT::Text  general-info: Details of the exchange action service response   # noqa: E501

        :return: The payments_exchange_action_response of this BQPaymentsExchangeOutputModel.
        :rtype: str
        """
        return self._payments_exchange_action_response

    @payments_exchange_action_response.setter
    def payments_exchange_action_response(self, payments_exchange_action_response):
        """Sets the payments_exchange_action_response of this BQPaymentsExchangeOutputModel.

        `status: Not Mapped`  core-data-type-reference: BIAN::DataTypesLibrary::CoreDataTypes::UNCEFACT::Text  general-info: Details of the exchange action service response   # noqa: E501

        :param payments_exchange_action_response: The payments_exchange_action_response of this BQPaymentsExchangeOutputModel.
        :type payments_exchange_action_response: str
        """

        self._payments_exchange_action_response = payments_exchange_action_response

    @property
    def payments_instance_status(self):
        """Gets the payments_instance_status of this BQPaymentsExchangeOutputModel.

        `status: Not Mapped`  core-data-type-reference: BIAN::DataTypesLibrary::CoreDataTypes::UNCEFACT::Text  general-info: The status of the Payments instance (e.g. accepted, rejected, verified)   # noqa: E501

        :return: The payments_instance_status of this BQPaymentsExchangeOutputModel.
        :rtype: str
        """
        return self._payments_instance_status

    @payments_instance_status.setter
    def payments_instance_status(self, payments_instance_status):
        """Sets the payments_instance_status of this BQPaymentsExchangeOutputModel.

        `status: Not Mapped`  core-data-type-reference: BIAN::DataTypesLibrary::CoreDataTypes::UNCEFACT::Text  general-info: The status of the Payments instance (e.g. accepted, rejected, verified)   # noqa: E501

        :param payments_instance_status: The payments_instance_status of this BQPaymentsExchangeOutputModel.
        :type payments_instance_status: str
        """

        self._payments_instance_status = payments_instance_status
