# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from tester.app.dto.base_model_ import Model
from tester.app.dto.bq_payments_retrieve_input_model_payments_instance_analysis1 import BQPaymentsRetrieveInputModelPaymentsInstanceAnalysis1
from tester.app.dto.bq_payments_retrieve_input_model_payments_instance_report1 import BQPaymentsRetrieveInputModelPaymentsInstanceReport1
from tester import util

from tester.app.dto.bq_payments_retrieve_input_model_payments_instance_analysis1 import BQPaymentsRetrieveInputModelPaymentsInstanceAnalysis1  # noqa: E501
from tester.app.dto.bq_payments_retrieve_input_model_payments_instance_report1 import BQPaymentsRetrieveInputModelPaymentsInstanceReport1  # noqa: E501



class BQPaymentsRetrieveInputModel(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, payments_retrieve_action_task_record=None, payments_retrieve_action_request=None, payments_instance_report=None, payments_instance_analysis=None):  # noqa: E501
        """BQPaymentsRetrieveInputModel - a model defined in OpenAPI

        :param payments_retrieve_action_task_record: The payments_retrieve_action_task_record of this BQPaymentsRetrieveInputModel.  # noqa: E501
        :type payments_retrieve_action_task_record: object
        :param payments_retrieve_action_request: The payments_retrieve_action_request of this BQPaymentsRetrieveInputModel.  # noqa: E501
        :type payments_retrieve_action_request: str
        :param payments_instance_report: The payments_instance_report of this BQPaymentsRetrieveInputModel.  # noqa: E501
        :type payments_instance_report: BQPaymentsRetrieveInputModelPaymentsInstanceReport1
        :param payments_instance_analysis: The payments_instance_analysis of this BQPaymentsRetrieveInputModel.  # noqa: E501
        :type payments_instance_analysis: BQPaymentsRetrieveInputModelPaymentsInstanceAnalysis1
        """
        self.openapi_types = {
            'payments_retrieve_action_task_record': object,
            'payments_retrieve_action_request': str,
            'payments_instance_report': BQPaymentsRetrieveInputModelPaymentsInstanceReport1,
            'payments_instance_analysis': BQPaymentsRetrieveInputModelPaymentsInstanceAnalysis1
        }

        self.attribute_map = {
            'payments_retrieve_action_task_record': 'paymentsRetrieveActionTaskRecord',
            'payments_retrieve_action_request': 'paymentsRetrieveActionRequest',
            'payments_instance_report': 'paymentsInstanceReport',
            'payments_instance_analysis': 'paymentsInstanceAnalysis'
        }

        self._payments_retrieve_action_task_record = payments_retrieve_action_task_record
        self._payments_retrieve_action_request = payments_retrieve_action_request
        self._payments_instance_report = payments_instance_report
        self._payments_instance_analysis = payments_instance_analysis

    @classmethod
    def from_dict(cls, dikt) -> 'BQPaymentsRetrieveInputModel':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The BQPaymentsRetrieveInputModel of this BQPaymentsRetrieveInputModel.  # noqa: E501
        :rtype: BQPaymentsRetrieveInputModel
        """
        return util.deserialize_model(dikt, cls)

    @property
    def payments_retrieve_action_task_record(self):
        """Gets the payments_retrieve_action_task_record of this BQPaymentsRetrieveInputModel.

        `status: Not Mapped`  core-data-type-reference: BIAN::DataTypesLibrary::CoreDataTypes::UNCEFACT::Binary  general-info: The retrieve service call consolidated processing record   # noqa: E501

        :return: The payments_retrieve_action_task_record of this BQPaymentsRetrieveInputModel.
        :rtype: object
        """
        return self._payments_retrieve_action_task_record

    @payments_retrieve_action_task_record.setter
    def payments_retrieve_action_task_record(self, payments_retrieve_action_task_record):
        """Sets the payments_retrieve_action_task_record of this BQPaymentsRetrieveInputModel.

        `status: Not Mapped`  core-data-type-reference: BIAN::DataTypesLibrary::CoreDataTypes::UNCEFACT::Binary  general-info: The retrieve service call consolidated processing record   # noqa: E501

        :param payments_retrieve_action_task_record: The payments_retrieve_action_task_record of this BQPaymentsRetrieveInputModel.
        :type payments_retrieve_action_task_record: object
        """

        self._payments_retrieve_action_task_record = payments_retrieve_action_task_record

    @property
    def payments_retrieve_action_request(self):
        """Gets the payments_retrieve_action_request of this BQPaymentsRetrieveInputModel.

        `status: Not Mapped`  core-data-type-reference: BIAN::DataTypesLibrary::CoreDataTypes::UNCEFACT::Text  general-info: Details of the retrieve action service request (lists requested reports)   # noqa: E501

        :return: The payments_retrieve_action_request of this BQPaymentsRetrieveInputModel.
        :rtype: str
        """
        return self._payments_retrieve_action_request

    @payments_retrieve_action_request.setter
    def payments_retrieve_action_request(self, payments_retrieve_action_request):
        """Sets the payments_retrieve_action_request of this BQPaymentsRetrieveInputModel.

        `status: Not Mapped`  core-data-type-reference: BIAN::DataTypesLibrary::CoreDataTypes::UNCEFACT::Text  general-info: Details of the retrieve action service request (lists requested reports)   # noqa: E501

        :param payments_retrieve_action_request: The payments_retrieve_action_request of this BQPaymentsRetrieveInputModel.
        :type payments_retrieve_action_request: str
        """

        self._payments_retrieve_action_request = payments_retrieve_action_request

    @property
    def payments_instance_report(self):
        """Gets the payments_instance_report of this BQPaymentsRetrieveInputModel.


        :return: The payments_instance_report of this BQPaymentsRetrieveInputModel.
        :rtype: BQPaymentsRetrieveInputModelPaymentsInstanceReport1
        """
        return self._payments_instance_report

    @payments_instance_report.setter
    def payments_instance_report(self, payments_instance_report):
        """Sets the payments_instance_report of this BQPaymentsRetrieveInputModel.


        :param payments_instance_report: The payments_instance_report of this BQPaymentsRetrieveInputModel.
        :type payments_instance_report: BQPaymentsRetrieveInputModelPaymentsInstanceReport1
        """

        self._payments_instance_report = payments_instance_report

    @property
    def payments_instance_analysis(self):
        """Gets the payments_instance_analysis of this BQPaymentsRetrieveInputModel.


        :return: The payments_instance_analysis of this BQPaymentsRetrieveInputModel.
        :rtype: BQPaymentsRetrieveInputModelPaymentsInstanceAnalysis1
        """
        return self._payments_instance_analysis

    @payments_instance_analysis.setter
    def payments_instance_analysis(self, payments_instance_analysis):
        """Sets the payments_instance_analysis of this BQPaymentsRetrieveInputModel.


        :param payments_instance_analysis: The payments_instance_analysis of this BQPaymentsRetrieveInputModel.
        :type payments_instance_analysis: BQPaymentsRetrieveInputModelPaymentsInstanceAnalysis1
        """

        self._payments_instance_analysis = payments_instance_analysis
