# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from tester.app.dto.base_model_ import Model
from tester.app.dto.current_account_sd_reference_id_current_account_fulfillment_arrangement_cr_reference_id_servicefees_initiation_current_account_fulfillment_arrangement_instance_record import CurrentAccountSdReferenceIdCurrentAccountFulfillmentArrangementCrReferenceIdServicefeesInitiationCurrentAccountFulfillmentArrangementInstanceRecord
from tester.app.dto.current_account_sd_reference_id_current_account_fulfillment_arrangement_cr_reference_id_servicefees_initiation_service_fees_instance_record import CurrentAccountSdReferenceIdCurrentAccountFulfillmentArrangementCrReferenceIdServicefeesInitiationServiceFeesInstanceRecord
from tester import util

from tester.app.dto.current_account_sd_reference_id_current_account_fulfillment_arrangement_cr_reference_id_servicefees_initiation_current_account_fulfillment_arrangement_instance_record import CurrentAccountSdReferenceIdCurrentAccountFulfillmentArrangementCrReferenceIdServicefeesInitiationCurrentAccountFulfillmentArrangementInstanceRecord  # noqa: E501
from tester.app.dto.current_account_sd_reference_id_current_account_fulfillment_arrangement_cr_reference_id_servicefees_initiation_service_fees_instance_record import CurrentAccountSdReferenceIdCurrentAccountFulfillmentArrangementCrReferenceIdServicefeesInitiationServiceFeesInstanceRecord  # noqa: E501



class BQServiceFeesInitiateInputModel(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, current_account_fulfillment_arrangement_instance_record=None, current_account_fulfillment_arrangement_instance_reference=None, service_fees_initiate_action_record=None, service_fees_instance_record=None):  # noqa: E501
        """BQServiceFeesInitiateInputModel - a model defined in OpenAPI

        :param current_account_fulfillment_arrangement_instance_record: The current_account_fulfillment_arrangement_instance_record of this BQServiceFeesInitiateInputModel.  # noqa: E501
        :type current_account_fulfillment_arrangement_instance_record: CurrentAccountSdReferenceIdCurrentAccountFulfillmentArrangementCrReferenceIdServicefeesInitiationCurrentAccountFulfillmentArrangementInstanceRecord
        :param current_account_fulfillment_arrangement_instance_reference: The current_account_fulfillment_arrangement_instance_reference of this BQServiceFeesInitiateInputModel.  # noqa: E501
        :type current_account_fulfillment_arrangement_instance_reference: str
        :param service_fees_initiate_action_record: The service_fees_initiate_action_record of this BQServiceFeesInitiateInputModel.  # noqa: E501
        :type service_fees_initiate_action_record: object
        :param service_fees_instance_record: The service_fees_instance_record of this BQServiceFeesInitiateInputModel.  # noqa: E501
        :type service_fees_instance_record: CurrentAccountSdReferenceIdCurrentAccountFulfillmentArrangementCrReferenceIdServicefeesInitiationServiceFeesInstanceRecord
        """
        self.openapi_types = {
            'current_account_fulfillment_arrangement_instance_record': CurrentAccountSdReferenceIdCurrentAccountFulfillmentArrangementCrReferenceIdServicefeesInitiationCurrentAccountFulfillmentArrangementInstanceRecord,
            'current_account_fulfillment_arrangement_instance_reference': str,
            'service_fees_initiate_action_record': object,
            'service_fees_instance_record': CurrentAccountSdReferenceIdCurrentAccountFulfillmentArrangementCrReferenceIdServicefeesInitiationServiceFeesInstanceRecord
        }

        self.attribute_map = {
            'current_account_fulfillment_arrangement_instance_record': 'currentAccountFulfillmentArrangementInstanceRecord',
            'current_account_fulfillment_arrangement_instance_reference': 'currentAccountFulfillmentArrangementInstanceReference',
            'service_fees_initiate_action_record': 'serviceFeesInitiateActionRecord',
            'service_fees_instance_record': 'serviceFeesInstanceRecord'
        }

        self._current_account_fulfillment_arrangement_instance_record = current_account_fulfillment_arrangement_instance_record
        self._current_account_fulfillment_arrangement_instance_reference = current_account_fulfillment_arrangement_instance_reference
        self._service_fees_initiate_action_record = service_fees_initiate_action_record
        self._service_fees_instance_record = service_fees_instance_record

    @classmethod
    def from_dict(cls, dikt) -> 'BQServiceFeesInitiateInputModel':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The BQServiceFeesInitiateInputModel of this BQServiceFeesInitiateInputModel.  # noqa: E501
        :rtype: BQServiceFeesInitiateInputModel
        """
        return util.deserialize_model(dikt, cls)

    @property
    def current_account_fulfillment_arrangement_instance_record(self):
        """Gets the current_account_fulfillment_arrangement_instance_record of this BQServiceFeesInitiateInputModel.


        :return: The current_account_fulfillment_arrangement_instance_record of this BQServiceFeesInitiateInputModel.
        :rtype: CurrentAccountSdReferenceIdCurrentAccountFulfillmentArrangementCrReferenceIdServicefeesInitiationCurrentAccountFulfillmentArrangementInstanceRecord
        """
        return self._current_account_fulfillment_arrangement_instance_record

    @current_account_fulfillment_arrangement_instance_record.setter
    def current_account_fulfillment_arrangement_instance_record(self, current_account_fulfillment_arrangement_instance_record):
        """Sets the current_account_fulfillment_arrangement_instance_record of this BQServiceFeesInitiateInputModel.


        :param current_account_fulfillment_arrangement_instance_record: The current_account_fulfillment_arrangement_instance_record of this BQServiceFeesInitiateInputModel.
        :type current_account_fulfillment_arrangement_instance_record: CurrentAccountSdReferenceIdCurrentAccountFulfillmentArrangementCrReferenceIdServicefeesInitiationCurrentAccountFulfillmentArrangementInstanceRecord
        """

        self._current_account_fulfillment_arrangement_instance_record = current_account_fulfillment_arrangement_instance_record

    @property
    def current_account_fulfillment_arrangement_instance_reference(self):
        """Gets the current_account_fulfillment_arrangement_instance_reference of this BQServiceFeesInitiateInputModel.

        `status: Not Mapped`  core-data-type-reference: BIAN::DataTypesLibrary::CoreDataTypes::ISO20022andUNCEFACT::Identifier  general-info: Reference to the parent Current Account Fulfillment Arrangement instance   # noqa: E501

        :return: The current_account_fulfillment_arrangement_instance_reference of this BQServiceFeesInitiateInputModel.
        :rtype: str
        """
        return self._current_account_fulfillment_arrangement_instance_reference

    @current_account_fulfillment_arrangement_instance_reference.setter
    def current_account_fulfillment_arrangement_instance_reference(self, current_account_fulfillment_arrangement_instance_reference):
        """Sets the current_account_fulfillment_arrangement_instance_reference of this BQServiceFeesInitiateInputModel.

        `status: Not Mapped`  core-data-type-reference: BIAN::DataTypesLibrary::CoreDataTypes::ISO20022andUNCEFACT::Identifier  general-info: Reference to the parent Current Account Fulfillment Arrangement instance   # noqa: E501

        :param current_account_fulfillment_arrangement_instance_reference: The current_account_fulfillment_arrangement_instance_reference of this BQServiceFeesInitiateInputModel.
        :type current_account_fulfillment_arrangement_instance_reference: str
        """

        self._current_account_fulfillment_arrangement_instance_reference = current_account_fulfillment_arrangement_instance_reference

    @property
    def service_fees_initiate_action_record(self):
        """Gets the service_fees_initiate_action_record of this BQServiceFeesInitiateInputModel.

        `status: Not Mapped`  core-data-type-reference: BIAN::DataTypesLibrary::CoreDataTypes::UNCEFACT::Binary  general-info: The Initiate service call input and output record   # noqa: E501

        :return: The service_fees_initiate_action_record of this BQServiceFeesInitiateInputModel.
        :rtype: object
        """
        return self._service_fees_initiate_action_record

    @service_fees_initiate_action_record.setter
    def service_fees_initiate_action_record(self, service_fees_initiate_action_record):
        """Sets the service_fees_initiate_action_record of this BQServiceFeesInitiateInputModel.

        `status: Not Mapped`  core-data-type-reference: BIAN::DataTypesLibrary::CoreDataTypes::UNCEFACT::Binary  general-info: The Initiate service call input and output record   # noqa: E501

        :param service_fees_initiate_action_record: The service_fees_initiate_action_record of this BQServiceFeesInitiateInputModel.
        :type service_fees_initiate_action_record: object
        """

        self._service_fees_initiate_action_record = service_fees_initiate_action_record

    @property
    def service_fees_instance_record(self):
        """Gets the service_fees_instance_record of this BQServiceFeesInitiateInputModel.


        :return: The service_fees_instance_record of this BQServiceFeesInitiateInputModel.
        :rtype: CurrentAccountSdReferenceIdCurrentAccountFulfillmentArrangementCrReferenceIdServicefeesInitiationServiceFeesInstanceRecord
        """
        return self._service_fees_instance_record

    @service_fees_instance_record.setter
    def service_fees_instance_record(self, service_fees_instance_record):
        """Sets the service_fees_instance_record of this BQServiceFeesInitiateInputModel.


        :param service_fees_instance_record: The service_fees_instance_record of this BQServiceFeesInitiateInputModel.
        :type service_fees_instance_record: CurrentAccountSdReferenceIdCurrentAccountFulfillmentArrangementCrReferenceIdServicefeesInitiationServiceFeesInstanceRecord
        """

        self._service_fees_instance_record = service_fees_instance_record
