# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from tester.app.dto.base_model_ import Model
from tester.app.dto.current_account_sd_reference_id_configuration_service_domain_service_configuration_record_service_domain_service_agreement import CurrentAccountSdReferenceIdConfigurationServiceDomainServiceConfigurationRecordServiceDomainServiceAgreement
from tester.app.dto.current_account_sd_reference_id_configuration_service_domain_service_configuration_record_service_domain_service_configuration_setup import CurrentAccountSdReferenceIdConfigurationServiceDomainServiceConfigurationRecordServiceDomainServiceConfigurationSetup
from tester.app.dto.current_account_sd_reference_id_configuration_service_domain_service_configuration_record_service_domain_service_subscription import CurrentAccountSdReferenceIdConfigurationServiceDomainServiceConfigurationRecordServiceDomainServiceSubscription
from tester import util

from tester.app.dto.current_account_sd_reference_id_configuration_service_domain_service_configuration_record_service_domain_service_agreement import CurrentAccountSdReferenceIdConfigurationServiceDomainServiceConfigurationRecordServiceDomainServiceAgreement  # noqa: E501
from tester.app.dto.current_account_sd_reference_id_configuration_service_domain_service_configuration_record_service_domain_service_configuration_setup import CurrentAccountSdReferenceIdConfigurationServiceDomainServiceConfigurationRecordServiceDomainServiceConfigurationSetup  # noqa: E501
from tester.app.dto.current_account_sd_reference_id_configuration_service_domain_service_configuration_record_service_domain_service_subscription import CurrentAccountSdReferenceIdConfigurationServiceDomainServiceConfigurationRecordServiceDomainServiceSubscription  # noqa: E501



class CurrentAccountSdReferenceIdConfigurationServiceDomainServiceConfigurationRecord(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, service_domain_service_configuration_setting_reference=None, service_domain_service_configuration_setting_type=None, service_domain_service_configuration_setup=None, service_domain_service_subscription=None, service_domain_service_agreement=None):  # noqa: E501
        """CurrentAccountSdReferenceIdConfigurationServiceDomainServiceConfigurationRecord - a model defined in OpenAPI

        :param service_domain_service_configuration_setting_reference: The service_domain_service_configuration_setting_reference of this CurrentAccountSdReferenceIdConfigurationServiceDomainServiceConfigurationRecord.  # noqa: E501
        :type service_domain_service_configuration_setting_reference: str
        :param service_domain_service_configuration_setting_type: The service_domain_service_configuration_setting_type of this CurrentAccountSdReferenceIdConfigurationServiceDomainServiceConfigurationRecord.  # noqa: E501
        :type service_domain_service_configuration_setting_type: str
        :param service_domain_service_configuration_setup: The service_domain_service_configuration_setup of this CurrentAccountSdReferenceIdConfigurationServiceDomainServiceConfigurationRecord.  # noqa: E501
        :type service_domain_service_configuration_setup: CurrentAccountSdReferenceIdConfigurationServiceDomainServiceConfigurationRecordServiceDomainServiceConfigurationSetup
        :param service_domain_service_subscription: The service_domain_service_subscription of this CurrentAccountSdReferenceIdConfigurationServiceDomainServiceConfigurationRecord.  # noqa: E501
        :type service_domain_service_subscription: CurrentAccountSdReferenceIdConfigurationServiceDomainServiceConfigurationRecordServiceDomainServiceSubscription
        :param service_domain_service_agreement: The service_domain_service_agreement of this CurrentAccountSdReferenceIdConfigurationServiceDomainServiceConfigurationRecord.  # noqa: E501
        :type service_domain_service_agreement: CurrentAccountSdReferenceIdConfigurationServiceDomainServiceConfigurationRecordServiceDomainServiceAgreement
        """
        self.openapi_types = {
            'service_domain_service_configuration_setting_reference': str,
            'service_domain_service_configuration_setting_type': str,
            'service_domain_service_configuration_setup': CurrentAccountSdReferenceIdConfigurationServiceDomainServiceConfigurationRecordServiceDomainServiceConfigurationSetup,
            'service_domain_service_subscription': CurrentAccountSdReferenceIdConfigurationServiceDomainServiceConfigurationRecordServiceDomainServiceSubscription,
            'service_domain_service_agreement': CurrentAccountSdReferenceIdConfigurationServiceDomainServiceConfigurationRecordServiceDomainServiceAgreement
        }

        self.attribute_map = {
            'service_domain_service_configuration_setting_reference': 'serviceDomainServiceConfigurationSettingReference',
            'service_domain_service_configuration_setting_type': 'serviceDomainServiceConfigurationSettingType',
            'service_domain_service_configuration_setup': 'serviceDomainServiceConfigurationSetup',
            'service_domain_service_subscription': 'serviceDomainServiceSubscription',
            'service_domain_service_agreement': 'serviceDomainServiceAgreement'
        }

        self._service_domain_service_configuration_setting_reference = service_domain_service_configuration_setting_reference
        self._service_domain_service_configuration_setting_type = service_domain_service_configuration_setting_type
        self._service_domain_service_configuration_setup = service_domain_service_configuration_setup
        self._service_domain_service_subscription = service_domain_service_subscription
        self._service_domain_service_agreement = service_domain_service_agreement

    @classmethod
    def from_dict(cls, dikt) -> 'CurrentAccountSdReferenceIdConfigurationServiceDomainServiceConfigurationRecord':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The _current_account__sd_reference_id__configuration_serviceDomainServiceConfigurationRecord of this CurrentAccountSdReferenceIdConfigurationServiceDomainServiceConfigurationRecord.  # noqa: E501
        :rtype: CurrentAccountSdReferenceIdConfigurationServiceDomainServiceConfigurationRecord
        """
        return util.deserialize_model(dikt, cls)

    @property
    def service_domain_service_configuration_setting_reference(self):
        """Gets the service_domain_service_configuration_setting_reference of this CurrentAccountSdReferenceIdConfigurationServiceDomainServiceConfigurationRecord.

        `status: Not Mapped`  core-data-type-reference: BIAN::DataTypesLibrary::CoreDataTypes::ISO20022andUNCEFACT::Identifier  general-info: Refers to the service configuration parameter for the service   # noqa: E501

        :return: The service_domain_service_configuration_setting_reference of this CurrentAccountSdReferenceIdConfigurationServiceDomainServiceConfigurationRecord.
        :rtype: str
        """
        return self._service_domain_service_configuration_setting_reference

    @service_domain_service_configuration_setting_reference.setter
    def service_domain_service_configuration_setting_reference(self, service_domain_service_configuration_setting_reference):
        """Sets the service_domain_service_configuration_setting_reference of this CurrentAccountSdReferenceIdConfigurationServiceDomainServiceConfigurationRecord.

        `status: Not Mapped`  core-data-type-reference: BIAN::DataTypesLibrary::CoreDataTypes::ISO20022andUNCEFACT::Identifier  general-info: Refers to the service configuration parameter for the service   # noqa: E501

        :param service_domain_service_configuration_setting_reference: The service_domain_service_configuration_setting_reference of this CurrentAccountSdReferenceIdConfigurationServiceDomainServiceConfigurationRecord.
        :type service_domain_service_configuration_setting_reference: str
        """

        self._service_domain_service_configuration_setting_reference = service_domain_service_configuration_setting_reference

    @property
    def service_domain_service_configuration_setting_type(self):
        """Gets the service_domain_service_configuration_setting_type of this CurrentAccountSdReferenceIdConfigurationServiceDomainServiceConfigurationRecord.

        `status: Not Mapped`  core-data-type-reference: BIAN::DataTypesLibrary::CoreDataTypes::UNCEFACT::Text  general-info: The type of service configuration parameter   # noqa: E501

        :return: The service_domain_service_configuration_setting_type of this CurrentAccountSdReferenceIdConfigurationServiceDomainServiceConfigurationRecord.
        :rtype: str
        """
        return self._service_domain_service_configuration_setting_type

    @service_domain_service_configuration_setting_type.setter
    def service_domain_service_configuration_setting_type(self, service_domain_service_configuration_setting_type):
        """Sets the service_domain_service_configuration_setting_type of this CurrentAccountSdReferenceIdConfigurationServiceDomainServiceConfigurationRecord.

        `status: Not Mapped`  core-data-type-reference: BIAN::DataTypesLibrary::CoreDataTypes::UNCEFACT::Text  general-info: The type of service configuration parameter   # noqa: E501

        :param service_domain_service_configuration_setting_type: The service_domain_service_configuration_setting_type of this CurrentAccountSdReferenceIdConfigurationServiceDomainServiceConfigurationRecord.
        :type service_domain_service_configuration_setting_type: str
        """

        self._service_domain_service_configuration_setting_type = service_domain_service_configuration_setting_type

    @property
    def service_domain_service_configuration_setup(self):
        """Gets the service_domain_service_configuration_setup of this CurrentAccountSdReferenceIdConfigurationServiceDomainServiceConfigurationRecord.


        :return: The service_domain_service_configuration_setup of this CurrentAccountSdReferenceIdConfigurationServiceDomainServiceConfigurationRecord.
        :rtype: CurrentAccountSdReferenceIdConfigurationServiceDomainServiceConfigurationRecordServiceDomainServiceConfigurationSetup
        """
        return self._service_domain_service_configuration_setup

    @service_domain_service_configuration_setup.setter
    def service_domain_service_configuration_setup(self, service_domain_service_configuration_setup):
        """Sets the service_domain_service_configuration_setup of this CurrentAccountSdReferenceIdConfigurationServiceDomainServiceConfigurationRecord.


        :param service_domain_service_configuration_setup: The service_domain_service_configuration_setup of this CurrentAccountSdReferenceIdConfigurationServiceDomainServiceConfigurationRecord.
        :type service_domain_service_configuration_setup: CurrentAccountSdReferenceIdConfigurationServiceDomainServiceConfigurationRecordServiceDomainServiceConfigurationSetup
        """

        self._service_domain_service_configuration_setup = service_domain_service_configuration_setup

    @property
    def service_domain_service_subscription(self):
        """Gets the service_domain_service_subscription of this CurrentAccountSdReferenceIdConfigurationServiceDomainServiceConfigurationRecord.


        :return: The service_domain_service_subscription of this CurrentAccountSdReferenceIdConfigurationServiceDomainServiceConfigurationRecord.
        :rtype: CurrentAccountSdReferenceIdConfigurationServiceDomainServiceConfigurationRecordServiceDomainServiceSubscription
        """
        return self._service_domain_service_subscription

    @service_domain_service_subscription.setter
    def service_domain_service_subscription(self, service_domain_service_subscription):
        """Sets the service_domain_service_subscription of this CurrentAccountSdReferenceIdConfigurationServiceDomainServiceConfigurationRecord.


        :param service_domain_service_subscription: The service_domain_service_subscription of this CurrentAccountSdReferenceIdConfigurationServiceDomainServiceConfigurationRecord.
        :type service_domain_service_subscription: CurrentAccountSdReferenceIdConfigurationServiceDomainServiceConfigurationRecordServiceDomainServiceSubscription
        """

        self._service_domain_service_subscription = service_domain_service_subscription

    @property
    def service_domain_service_agreement(self):
        """Gets the service_domain_service_agreement of this CurrentAccountSdReferenceIdConfigurationServiceDomainServiceConfigurationRecord.


        :return: The service_domain_service_agreement of this CurrentAccountSdReferenceIdConfigurationServiceDomainServiceConfigurationRecord.
        :rtype: CurrentAccountSdReferenceIdConfigurationServiceDomainServiceConfigurationRecordServiceDomainServiceAgreement
        """
        return self._service_domain_service_agreement

    @service_domain_service_agreement.setter
    def service_domain_service_agreement(self, service_domain_service_agreement):
        """Sets the service_domain_service_agreement of this CurrentAccountSdReferenceIdConfigurationServiceDomainServiceConfigurationRecord.


        :param service_domain_service_agreement: The service_domain_service_agreement of this CurrentAccountSdReferenceIdConfigurationServiceDomainServiceConfigurationRecord.
        :type service_domain_service_agreement: CurrentAccountSdReferenceIdConfigurationServiceDomainServiceConfigurationRecordServiceDomainServiceAgreement
        """

        self._service_domain_service_agreement = service_domain_service_agreement
