# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from tester.app.dto.base_model_ import Model
from tester.app.dto.current_account_sd_reference_id_current_account_fulfillment_arrangement_cr_reference_id_servicefees_bq_reference_id_execution_execute_record_type import CurrentAccountSdReferenceIdCurrentAccountFulfillmentArrangementCrReferenceIdServicefeesBqReferenceIdExecutionExecuteRecordType
from tester.app.dto.current_account_sd_reference_id_current_account_fulfillment_arrangement_cr_reference_id_servicefees_bq_reference_id_execution_service_fees_instance_record import CurrentAccountSdReferenceIdCurrentAccountFulfillmentArrangementCrReferenceIdServicefeesBqReferenceIdExecutionServiceFeesInstanceRecord
from tester import util

from tester.app.dto.current_account_sd_reference_id_current_account_fulfillment_arrangement_cr_reference_id_servicefees_bq_reference_id_execution_execute_record_type import CurrentAccountSdReferenceIdCurrentAccountFulfillmentArrangementCrReferenceIdServicefeesBqReferenceIdExecutionExecuteRecordType  # noqa: E501
from tester.app.dto.current_account_sd_reference_id_current_account_fulfillment_arrangement_cr_reference_id_servicefees_bq_reference_id_execution_service_fees_instance_record import CurrentAccountSdReferenceIdCurrentAccountFulfillmentArrangementCrReferenceIdServicefeesBqReferenceIdExecutionServiceFeesInstanceRecord  # noqa: E501



class InlineObject7(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, current_account_fulfillment_arrangement_instance_reference=None, service_fees_instance_reference=None, service_fees_instance_record=None, service_fees_execute_action_task_record=None, execute_record_type=None):  # noqa: E501
        """InlineObject7 - a model defined in OpenAPI

        :param current_account_fulfillment_arrangement_instance_reference: The current_account_fulfillment_arrangement_instance_reference of this InlineObject7.  # noqa: E501
        :type current_account_fulfillment_arrangement_instance_reference: str
        :param service_fees_instance_reference: The service_fees_instance_reference of this InlineObject7.  # noqa: E501
        :type service_fees_instance_reference: str
        :param service_fees_instance_record: The service_fees_instance_record of this InlineObject7.  # noqa: E501
        :type service_fees_instance_record: CurrentAccountSdReferenceIdCurrentAccountFulfillmentArrangementCrReferenceIdServicefeesBqReferenceIdExecutionServiceFeesInstanceRecord
        :param service_fees_execute_action_task_record: The service_fees_execute_action_task_record of this InlineObject7.  # noqa: E501
        :type service_fees_execute_action_task_record: object
        :param execute_record_type: The execute_record_type of this InlineObject7.  # noqa: E501
        :type execute_record_type: CurrentAccountSdReferenceIdCurrentAccountFulfillmentArrangementCrReferenceIdServicefeesBqReferenceIdExecutionExecuteRecordType
        """
        self.openapi_types = {
            'current_account_fulfillment_arrangement_instance_reference': str,
            'service_fees_instance_reference': str,
            'service_fees_instance_record': CurrentAccountSdReferenceIdCurrentAccountFulfillmentArrangementCrReferenceIdServicefeesBqReferenceIdExecutionServiceFeesInstanceRecord,
            'service_fees_execute_action_task_record': object,
            'execute_record_type': CurrentAccountSdReferenceIdCurrentAccountFulfillmentArrangementCrReferenceIdServicefeesBqReferenceIdExecutionExecuteRecordType
        }

        self.attribute_map = {
            'current_account_fulfillment_arrangement_instance_reference': 'currentAccountFulfillmentArrangementInstanceReference',
            'service_fees_instance_reference': 'serviceFeesInstanceReference',
            'service_fees_instance_record': 'serviceFeesInstanceRecord',
            'service_fees_execute_action_task_record': 'serviceFeesExecuteActionTaskRecord',
            'execute_record_type': 'executeRecordType'
        }

        self._current_account_fulfillment_arrangement_instance_reference = current_account_fulfillment_arrangement_instance_reference
        self._service_fees_instance_reference = service_fees_instance_reference
        self._service_fees_instance_record = service_fees_instance_record
        self._service_fees_execute_action_task_record = service_fees_execute_action_task_record
        self._execute_record_type = execute_record_type

    @classmethod
    def from_dict(cls, dikt) -> 'InlineObject7':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The inline_object_7 of this InlineObject7.  # noqa: E501
        :rtype: InlineObject7
        """
        return util.deserialize_model(dikt, cls)

    @property
    def current_account_fulfillment_arrangement_instance_reference(self):
        """Gets the current_account_fulfillment_arrangement_instance_reference of this InlineObject7.

        `status: Not Mapped`  core-data-type-reference: BIAN::DataTypesLibrary::CoreDataTypes::ISO20022andUNCEFACT::Identifier  general-info: Reference to the parent Current Account Fulfillment Arrangement instance   # noqa: E501

        :return: The current_account_fulfillment_arrangement_instance_reference of this InlineObject7.
        :rtype: str
        """
        return self._current_account_fulfillment_arrangement_instance_reference

    @current_account_fulfillment_arrangement_instance_reference.setter
    def current_account_fulfillment_arrangement_instance_reference(self, current_account_fulfillment_arrangement_instance_reference):
        """Sets the current_account_fulfillment_arrangement_instance_reference of this InlineObject7.

        `status: Not Mapped`  core-data-type-reference: BIAN::DataTypesLibrary::CoreDataTypes::ISO20022andUNCEFACT::Identifier  general-info: Reference to the parent Current Account Fulfillment Arrangement instance   # noqa: E501

        :param current_account_fulfillment_arrangement_instance_reference: The current_account_fulfillment_arrangement_instance_reference of this InlineObject7.
        :type current_account_fulfillment_arrangement_instance_reference: str
        """

        self._current_account_fulfillment_arrangement_instance_reference = current_account_fulfillment_arrangement_instance_reference

    @property
    def service_fees_instance_reference(self):
        """Gets the service_fees_instance_reference of this InlineObject7.

        `status: Not Mapped`  core-data-type-reference: BIAN::DataTypesLibrary::CoreDataTypes::ISO20022andUNCEFACT::Identifier  general-info: Reference to the Service Fees instance   # noqa: E501

        :return: The service_fees_instance_reference of this InlineObject7.
        :rtype: str
        """
        return self._service_fees_instance_reference

    @service_fees_instance_reference.setter
    def service_fees_instance_reference(self, service_fees_instance_reference):
        """Sets the service_fees_instance_reference of this InlineObject7.

        `status: Not Mapped`  core-data-type-reference: BIAN::DataTypesLibrary::CoreDataTypes::ISO20022andUNCEFACT::Identifier  general-info: Reference to the Service Fees instance   # noqa: E501

        :param service_fees_instance_reference: The service_fees_instance_reference of this InlineObject7.
        :type service_fees_instance_reference: str
        """

        self._service_fees_instance_reference = service_fees_instance_reference

    @property
    def service_fees_instance_record(self):
        """Gets the service_fees_instance_record of this InlineObject7.


        :return: The service_fees_instance_record of this InlineObject7.
        :rtype: CurrentAccountSdReferenceIdCurrentAccountFulfillmentArrangementCrReferenceIdServicefeesBqReferenceIdExecutionServiceFeesInstanceRecord
        """
        return self._service_fees_instance_record

    @service_fees_instance_record.setter
    def service_fees_instance_record(self, service_fees_instance_record):
        """Sets the service_fees_instance_record of this InlineObject7.


        :param service_fees_instance_record: The service_fees_instance_record of this InlineObject7.
        :type service_fees_instance_record: CurrentAccountSdReferenceIdCurrentAccountFulfillmentArrangementCrReferenceIdServicefeesBqReferenceIdExecutionServiceFeesInstanceRecord
        """

        self._service_fees_instance_record = service_fees_instance_record

    @property
    def service_fees_execute_action_task_record(self):
        """Gets the service_fees_execute_action_task_record of this InlineObject7.

        `status: Not Mapped`  core-data-type-reference: BIAN::DataTypesLibrary::CoreDataTypes::UNCEFACT::Binary  general-info: The execute service call consolidated processing record   # noqa: E501

        :return: The service_fees_execute_action_task_record of this InlineObject7.
        :rtype: object
        """
        return self._service_fees_execute_action_task_record

    @service_fees_execute_action_task_record.setter
    def service_fees_execute_action_task_record(self, service_fees_execute_action_task_record):
        """Sets the service_fees_execute_action_task_record of this InlineObject7.

        `status: Not Mapped`  core-data-type-reference: BIAN::DataTypesLibrary::CoreDataTypes::UNCEFACT::Binary  general-info: The execute service call consolidated processing record   # noqa: E501

        :param service_fees_execute_action_task_record: The service_fees_execute_action_task_record of this InlineObject7.
        :type service_fees_execute_action_task_record: object
        """

        self._service_fees_execute_action_task_record = service_fees_execute_action_task_record

    @property
    def execute_record_type(self):
        """Gets the execute_record_type of this InlineObject7.


        :return: The execute_record_type of this InlineObject7.
        :rtype: CurrentAccountSdReferenceIdCurrentAccountFulfillmentArrangementCrReferenceIdServicefeesBqReferenceIdExecutionExecuteRecordType
        """
        return self._execute_record_type

    @execute_record_type.setter
    def execute_record_type(self, execute_record_type):
        """Sets the execute_record_type of this InlineObject7.


        :param execute_record_type: The execute_record_type of this InlineObject7.
        :type execute_record_type: CurrentAccountSdReferenceIdCurrentAccountFulfillmentArrangementCrReferenceIdServicefeesBqReferenceIdExecutionExecuteRecordType
        """

        self._execute_record_type = execute_record_type
