# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from tester.app.dto.base_model_ import Model
from tester import util




class InlineResponse2002ServiceDomainRetrieveActionRecordServiceDomainPerformanceAnalysis(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, performance_analysis_reference=None, performance_analysis_result=None, performance_analysis_report_type=None, performance_analysis_report=None):  # noqa: E501
        """InlineResponse2002ServiceDomainRetrieveActionRecordServiceDomainPerformanceAnalysis - a model defined in OpenAPI

        :param performance_analysis_reference: The performance_analysis_reference of this InlineResponse2002ServiceDomainRetrieveActionRecordServiceDomainPerformanceAnalysis.  # noqa: E501
        :type performance_analysis_reference: str
        :param performance_analysis_result: The performance_analysis_result of this InlineResponse2002ServiceDomainRetrieveActionRecordServiceDomainPerformanceAnalysis.  # noqa: E501
        :type performance_analysis_result: str
        :param performance_analysis_report_type: The performance_analysis_report_type of this InlineResponse2002ServiceDomainRetrieveActionRecordServiceDomainPerformanceAnalysis.  # noqa: E501
        :type performance_analysis_report_type: str
        :param performance_analysis_report: The performance_analysis_report of this InlineResponse2002ServiceDomainRetrieveActionRecordServiceDomainPerformanceAnalysis.  # noqa: E501
        :type performance_analysis_report: object
        """
        self.openapi_types = {
            'performance_analysis_reference': str,
            'performance_analysis_result': str,
            'performance_analysis_report_type': str,
            'performance_analysis_report': object
        }

        self.attribute_map = {
            'performance_analysis_reference': 'performanceAnalysisReference',
            'performance_analysis_result': 'performanceAnalysisResult',
            'performance_analysis_report_type': 'performanceAnalysisReportType',
            'performance_analysis_report': 'performanceAnalysisReport'
        }

        self._performance_analysis_reference = performance_analysis_reference
        self._performance_analysis_result = performance_analysis_result
        self._performance_analysis_report_type = performance_analysis_report_type
        self._performance_analysis_report = performance_analysis_report

    @classmethod
    def from_dict(cls, dikt) -> 'InlineResponse2002ServiceDomainRetrieveActionRecordServiceDomainPerformanceAnalysis':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The inline_response_200_2_serviceDomainRetrieveActionRecord_serviceDomainPerformanceAnalysis of this InlineResponse2002ServiceDomainRetrieveActionRecordServiceDomainPerformanceAnalysis.  # noqa: E501
        :rtype: InlineResponse2002ServiceDomainRetrieveActionRecordServiceDomainPerformanceAnalysis
        """
        return util.deserialize_model(dikt, cls)

    @property
    def performance_analysis_reference(self):
        """Gets the performance_analysis_reference of this InlineResponse2002ServiceDomainRetrieveActionRecordServiceDomainPerformanceAnalysis.

        `status: Not Mapped`  core-data-type-reference: BIAN::DataTypesLibrary::CoreDataTypes::ISO20022andUNCEFACT::Identifier  general-info: Reference to the internal performance analysis view maintained by the service center   # noqa: E501

        :return: The performance_analysis_reference of this InlineResponse2002ServiceDomainRetrieveActionRecordServiceDomainPerformanceAnalysis.
        :rtype: str
        """
        return self._performance_analysis_reference

    @performance_analysis_reference.setter
    def performance_analysis_reference(self, performance_analysis_reference):
        """Sets the performance_analysis_reference of this InlineResponse2002ServiceDomainRetrieveActionRecordServiceDomainPerformanceAnalysis.

        `status: Not Mapped`  core-data-type-reference: BIAN::DataTypesLibrary::CoreDataTypes::ISO20022andUNCEFACT::Identifier  general-info: Reference to the internal performance analysis view maintained by the service center   # noqa: E501

        :param performance_analysis_reference: The performance_analysis_reference of this InlineResponse2002ServiceDomainRetrieveActionRecordServiceDomainPerformanceAnalysis.
        :type performance_analysis_reference: str
        """

        self._performance_analysis_reference = performance_analysis_reference

    @property
    def performance_analysis_result(self):
        """Gets the performance_analysis_result of this InlineResponse2002ServiceDomainRetrieveActionRecordServiceDomainPerformanceAnalysis.

        `status: Not Mapped`  core-data-type-reference: BIAN::DataTypesLibrary::CoreDataTypes::UNCEFACT::Text  general-info: The results of the performance analysis that can be on-going or periodic   # noqa: E501

        :return: The performance_analysis_result of this InlineResponse2002ServiceDomainRetrieveActionRecordServiceDomainPerformanceAnalysis.
        :rtype: str
        """
        return self._performance_analysis_result

    @performance_analysis_result.setter
    def performance_analysis_result(self, performance_analysis_result):
        """Sets the performance_analysis_result of this InlineResponse2002ServiceDomainRetrieveActionRecordServiceDomainPerformanceAnalysis.

        `status: Not Mapped`  core-data-type-reference: BIAN::DataTypesLibrary::CoreDataTypes::UNCEFACT::Text  general-info: The results of the performance analysis that can be on-going or periodic   # noqa: E501

        :param performance_analysis_result: The performance_analysis_result of this InlineResponse2002ServiceDomainRetrieveActionRecordServiceDomainPerformanceAnalysis.
        :type performance_analysis_result: str
        """

        self._performance_analysis_result = performance_analysis_result

    @property
    def performance_analysis_report_type(self):
        """Gets the performance_analysis_report_type of this InlineResponse2002ServiceDomainRetrieveActionRecordServiceDomainPerformanceAnalysis.

        `status: Not Mapped`  core-data-type-reference: BIAN::DataTypesLibrary::CoreDataTypes::UNCEFACT::Code  general-info: The type of performance analysis report available   # noqa: E501

        :return: The performance_analysis_report_type of this InlineResponse2002ServiceDomainRetrieveActionRecordServiceDomainPerformanceAnalysis.
        :rtype: str
        """
        return self._performance_analysis_report_type

    @performance_analysis_report_type.setter
    def performance_analysis_report_type(self, performance_analysis_report_type):
        """Sets the performance_analysis_report_type of this InlineResponse2002ServiceDomainRetrieveActionRecordServiceDomainPerformanceAnalysis.

        `status: Not Mapped`  core-data-type-reference: BIAN::DataTypesLibrary::CoreDataTypes::UNCEFACT::Code  general-info: The type of performance analysis report available   # noqa: E501

        :param performance_analysis_report_type: The performance_analysis_report_type of this InlineResponse2002ServiceDomainRetrieveActionRecordServiceDomainPerformanceAnalysis.
        :type performance_analysis_report_type: str
        """

        self._performance_analysis_report_type = performance_analysis_report_type

    @property
    def performance_analysis_report(self):
        """Gets the performance_analysis_report of this InlineResponse2002ServiceDomainRetrieveActionRecordServiceDomainPerformanceAnalysis.

        `status: Not Mapped`  core-data-type-reference: BIAN::DataTypesLibrary::CoreDataTypes::UNCEFACT::Binary  general-info: The performance analysis report in any suitable form including selection filters where appropriate   # noqa: E501

        :return: The performance_analysis_report of this InlineResponse2002ServiceDomainRetrieveActionRecordServiceDomainPerformanceAnalysis.
        :rtype: object
        """
        return self._performance_analysis_report

    @performance_analysis_report.setter
    def performance_analysis_report(self, performance_analysis_report):
        """Sets the performance_analysis_report of this InlineResponse2002ServiceDomainRetrieveActionRecordServiceDomainPerformanceAnalysis.

        `status: Not Mapped`  core-data-type-reference: BIAN::DataTypesLibrary::CoreDataTypes::UNCEFACT::Binary  general-info: The performance analysis report in any suitable form including selection filters where appropriate   # noqa: E501

        :param performance_analysis_report: The performance_analysis_report of this InlineResponse2002ServiceDomainRetrieveActionRecordServiceDomainPerformanceAnalysis.
        :type performance_analysis_report: object
        """

        self._performance_analysis_report = performance_analysis_report
