# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from tester.app.dto.base_model_ import Model
from tester.app.dto.inline_response2002_service_domain_offered_service import InlineResponse2002ServiceDomainOfferedService
from tester.app.dto.inline_response2002_service_domain_retrieve_action_record import InlineResponse2002ServiceDomainRetrieveActionRecord
from tester import util

from tester.app.dto.inline_response2002_service_domain_offered_service import InlineResponse2002ServiceDomainOfferedService  # noqa: E501
from tester.app.dto.inline_response2002_service_domain_retrieve_action_record import InlineResponse2002ServiceDomainRetrieveActionRecord  # noqa: E501



class InlineResponse2002(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, service_domain_retrieve_action_task_reference=None, service_domain_retrieve_action_task_record=None, service_domain_retrieve_action_response=None, service_domain_retrieve_action_record=None, service_domain_offered_service=None):  # noqa: E501
        """InlineResponse2002 - a model defined in OpenAPI

        :param service_domain_retrieve_action_task_reference: The service_domain_retrieve_action_task_reference of this InlineResponse2002.  # noqa: E501
        :type service_domain_retrieve_action_task_reference: str
        :param service_domain_retrieve_action_task_record: The service_domain_retrieve_action_task_record of this InlineResponse2002.  # noqa: E501
        :type service_domain_retrieve_action_task_record: object
        :param service_domain_retrieve_action_response: The service_domain_retrieve_action_response of this InlineResponse2002.  # noqa: E501
        :type service_domain_retrieve_action_response: str
        :param service_domain_retrieve_action_record: The service_domain_retrieve_action_record of this InlineResponse2002.  # noqa: E501
        :type service_domain_retrieve_action_record: InlineResponse2002ServiceDomainRetrieveActionRecord
        :param service_domain_offered_service: The service_domain_offered_service of this InlineResponse2002.  # noqa: E501
        :type service_domain_offered_service: InlineResponse2002ServiceDomainOfferedService
        """
        self.openapi_types = {
            'service_domain_retrieve_action_task_reference': str,
            'service_domain_retrieve_action_task_record': object,
            'service_domain_retrieve_action_response': str,
            'service_domain_retrieve_action_record': InlineResponse2002ServiceDomainRetrieveActionRecord,
            'service_domain_offered_service': InlineResponse2002ServiceDomainOfferedService
        }

        self.attribute_map = {
            'service_domain_retrieve_action_task_reference': 'serviceDomainRetrieveActionTaskReference',
            'service_domain_retrieve_action_task_record': 'serviceDomainRetrieveActionTaskRecord',
            'service_domain_retrieve_action_response': 'serviceDomainRetrieveActionResponse',
            'service_domain_retrieve_action_record': 'serviceDomainRetrieveActionRecord',
            'service_domain_offered_service': 'serviceDomainOfferedService'
        }

        self._service_domain_retrieve_action_task_reference = service_domain_retrieve_action_task_reference
        self._service_domain_retrieve_action_task_record = service_domain_retrieve_action_task_record
        self._service_domain_retrieve_action_response = service_domain_retrieve_action_response
        self._service_domain_retrieve_action_record = service_domain_retrieve_action_record
        self._service_domain_offered_service = service_domain_offered_service

    @classmethod
    def from_dict(cls, dikt) -> 'InlineResponse2002':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The inline_response_200_2 of this InlineResponse2002.  # noqa: E501
        :rtype: InlineResponse2002
        """
        return util.deserialize_model(dikt, cls)

    @property
    def service_domain_retrieve_action_task_reference(self):
        """Gets the service_domain_retrieve_action_task_reference of this InlineResponse2002.

        `status: Not Mapped`  core-data-type-reference: BIAN::DataTypesLibrary::CoreDataTypes::ISO20022andUNCEFACT::Identifier  general-info: Reference to a retrieve service call   # noqa: E501

        :return: The service_domain_retrieve_action_task_reference of this InlineResponse2002.
        :rtype: str
        """
        return self._service_domain_retrieve_action_task_reference

    @service_domain_retrieve_action_task_reference.setter
    def service_domain_retrieve_action_task_reference(self, service_domain_retrieve_action_task_reference):
        """Sets the service_domain_retrieve_action_task_reference of this InlineResponse2002.

        `status: Not Mapped`  core-data-type-reference: BIAN::DataTypesLibrary::CoreDataTypes::ISO20022andUNCEFACT::Identifier  general-info: Reference to a retrieve service call   # noqa: E501

        :param service_domain_retrieve_action_task_reference: The service_domain_retrieve_action_task_reference of this InlineResponse2002.
        :type service_domain_retrieve_action_task_reference: str
        """

        self._service_domain_retrieve_action_task_reference = service_domain_retrieve_action_task_reference

    @property
    def service_domain_retrieve_action_task_record(self):
        """Gets the service_domain_retrieve_action_task_record of this InlineResponse2002.

        `status: Not Mapped`  core-data-type-reference: BIAN::DataTypesLibrary::CoreDataTypes::UNCEFACT::Binary  general-info: The retrieve service call consolidated processing record   # noqa: E501

        :return: The service_domain_retrieve_action_task_record of this InlineResponse2002.
        :rtype: object
        """
        return self._service_domain_retrieve_action_task_record

    @service_domain_retrieve_action_task_record.setter
    def service_domain_retrieve_action_task_record(self, service_domain_retrieve_action_task_record):
        """Sets the service_domain_retrieve_action_task_record of this InlineResponse2002.

        `status: Not Mapped`  core-data-type-reference: BIAN::DataTypesLibrary::CoreDataTypes::UNCEFACT::Binary  general-info: The retrieve service call consolidated processing record   # noqa: E501

        :param service_domain_retrieve_action_task_record: The service_domain_retrieve_action_task_record of this InlineResponse2002.
        :type service_domain_retrieve_action_task_record: object
        """

        self._service_domain_retrieve_action_task_record = service_domain_retrieve_action_task_record

    @property
    def service_domain_retrieve_action_response(self):
        """Gets the service_domain_retrieve_action_response of this InlineResponse2002.

        `status: Not Mapped`  core-data-type-reference: BIAN::DataTypesLibrary::CoreDataTypes::UNCEFACT::Text  general-info: Details of the retrieve action service response (lists returned reports)   # noqa: E501

        :return: The service_domain_retrieve_action_response of this InlineResponse2002.
        :rtype: str
        """
        return self._service_domain_retrieve_action_response

    @service_domain_retrieve_action_response.setter
    def service_domain_retrieve_action_response(self, service_domain_retrieve_action_response):
        """Sets the service_domain_retrieve_action_response of this InlineResponse2002.

        `status: Not Mapped`  core-data-type-reference: BIAN::DataTypesLibrary::CoreDataTypes::UNCEFACT::Text  general-info: Details of the retrieve action service response (lists returned reports)   # noqa: E501

        :param service_domain_retrieve_action_response: The service_domain_retrieve_action_response of this InlineResponse2002.
        :type service_domain_retrieve_action_response: str
        """

        self._service_domain_retrieve_action_response = service_domain_retrieve_action_response

    @property
    def service_domain_retrieve_action_record(self):
        """Gets the service_domain_retrieve_action_record of this InlineResponse2002.


        :return: The service_domain_retrieve_action_record of this InlineResponse2002.
        :rtype: InlineResponse2002ServiceDomainRetrieveActionRecord
        """
        return self._service_domain_retrieve_action_record

    @service_domain_retrieve_action_record.setter
    def service_domain_retrieve_action_record(self, service_domain_retrieve_action_record):
        """Sets the service_domain_retrieve_action_record of this InlineResponse2002.


        :param service_domain_retrieve_action_record: The service_domain_retrieve_action_record of this InlineResponse2002.
        :type service_domain_retrieve_action_record: InlineResponse2002ServiceDomainRetrieveActionRecord
        """

        self._service_domain_retrieve_action_record = service_domain_retrieve_action_record

    @property
    def service_domain_offered_service(self):
        """Gets the service_domain_offered_service of this InlineResponse2002.


        :return: The service_domain_offered_service of this InlineResponse2002.
        :rtype: InlineResponse2002ServiceDomainOfferedService
        """
        return self._service_domain_offered_service

    @service_domain_offered_service.setter
    def service_domain_offered_service(self, service_domain_offered_service):
        """Sets the service_domain_offered_service of this InlineResponse2002.


        :param service_domain_offered_service: The service_domain_offered_service of this InlineResponse2002.
        :type service_domain_offered_service: InlineResponse2002ServiceDomainOfferedService
        """

        self._service_domain_offered_service = service_domain_offered_service
