# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from tester.app.dto.base_model_ import Model
from tester.app.dto.inline_response2008_service_fees_instance_analysis import InlineResponse2008ServiceFeesInstanceAnalysis
from tester.app.dto.inline_response2008_service_fees_instance_record import InlineResponse2008ServiceFeesInstanceRecord
from tester.app.dto.inline_response2008_service_fees_instance_report import InlineResponse2008ServiceFeesInstanceReport
from tester import util

from tester.app.dto.inline_response2008_service_fees_instance_analysis import InlineResponse2008ServiceFeesInstanceAnalysis  # noqa: E501
from tester.app.dto.inline_response2008_service_fees_instance_record import InlineResponse2008ServiceFeesInstanceRecord  # noqa: E501
from tester.app.dto.inline_response2008_service_fees_instance_report import InlineResponse2008ServiceFeesInstanceReport  # noqa: E501



class InlineResponse2008(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, service_fees_instance_record=None, service_fees_retrieve_action_task_reference=None, service_fees_retrieve_action_task_record=None, service_fees_retrieve_action_response=None, service_fees_instance_report=None, service_fees_instance_analysis=None):  # noqa: E501
        """InlineResponse2008 - a model defined in OpenAPI

        :param service_fees_instance_record: The service_fees_instance_record of this InlineResponse2008.  # noqa: E501
        :type service_fees_instance_record: InlineResponse2008ServiceFeesInstanceRecord
        :param service_fees_retrieve_action_task_reference: The service_fees_retrieve_action_task_reference of this InlineResponse2008.  # noqa: E501
        :type service_fees_retrieve_action_task_reference: str
        :param service_fees_retrieve_action_task_record: The service_fees_retrieve_action_task_record of this InlineResponse2008.  # noqa: E501
        :type service_fees_retrieve_action_task_record: object
        :param service_fees_retrieve_action_response: The service_fees_retrieve_action_response of this InlineResponse2008.  # noqa: E501
        :type service_fees_retrieve_action_response: str
        :param service_fees_instance_report: The service_fees_instance_report of this InlineResponse2008.  # noqa: E501
        :type service_fees_instance_report: InlineResponse2008ServiceFeesInstanceReport
        :param service_fees_instance_analysis: The service_fees_instance_analysis of this InlineResponse2008.  # noqa: E501
        :type service_fees_instance_analysis: InlineResponse2008ServiceFeesInstanceAnalysis
        """
        self.openapi_types = {
            'service_fees_instance_record': InlineResponse2008ServiceFeesInstanceRecord,
            'service_fees_retrieve_action_task_reference': str,
            'service_fees_retrieve_action_task_record': object,
            'service_fees_retrieve_action_response': str,
            'service_fees_instance_report': InlineResponse2008ServiceFeesInstanceReport,
            'service_fees_instance_analysis': InlineResponse2008ServiceFeesInstanceAnalysis
        }

        self.attribute_map = {
            'service_fees_instance_record': 'serviceFeesInstanceRecord',
            'service_fees_retrieve_action_task_reference': 'serviceFeesRetrieveActionTaskReference',
            'service_fees_retrieve_action_task_record': 'serviceFeesRetrieveActionTaskRecord',
            'service_fees_retrieve_action_response': 'serviceFeesRetrieveActionResponse',
            'service_fees_instance_report': 'serviceFeesInstanceReport',
            'service_fees_instance_analysis': 'serviceFeesInstanceAnalysis'
        }

        self._service_fees_instance_record = service_fees_instance_record
        self._service_fees_retrieve_action_task_reference = service_fees_retrieve_action_task_reference
        self._service_fees_retrieve_action_task_record = service_fees_retrieve_action_task_record
        self._service_fees_retrieve_action_response = service_fees_retrieve_action_response
        self._service_fees_instance_report = service_fees_instance_report
        self._service_fees_instance_analysis = service_fees_instance_analysis

    @classmethod
    def from_dict(cls, dikt) -> 'InlineResponse2008':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The inline_response_200_8 of this InlineResponse2008.  # noqa: E501
        :rtype: InlineResponse2008
        """
        return util.deserialize_model(dikt, cls)

    @property
    def service_fees_instance_record(self):
        """Gets the service_fees_instance_record of this InlineResponse2008.


        :return: The service_fees_instance_record of this InlineResponse2008.
        :rtype: InlineResponse2008ServiceFeesInstanceRecord
        """
        return self._service_fees_instance_record

    @service_fees_instance_record.setter
    def service_fees_instance_record(self, service_fees_instance_record):
        """Sets the service_fees_instance_record of this InlineResponse2008.


        :param service_fees_instance_record: The service_fees_instance_record of this InlineResponse2008.
        :type service_fees_instance_record: InlineResponse2008ServiceFeesInstanceRecord
        """

        self._service_fees_instance_record = service_fees_instance_record

    @property
    def service_fees_retrieve_action_task_reference(self):
        """Gets the service_fees_retrieve_action_task_reference of this InlineResponse2008.

        `status: Not Mapped`  core-data-type-reference: BIAN::DataTypesLibrary::CoreDataTypes::ISO20022andUNCEFACT::Identifier  general-info: Reference to a Service Fees instance retrieve service call   # noqa: E501

        :return: The service_fees_retrieve_action_task_reference of this InlineResponse2008.
        :rtype: str
        """
        return self._service_fees_retrieve_action_task_reference

    @service_fees_retrieve_action_task_reference.setter
    def service_fees_retrieve_action_task_reference(self, service_fees_retrieve_action_task_reference):
        """Sets the service_fees_retrieve_action_task_reference of this InlineResponse2008.

        `status: Not Mapped`  core-data-type-reference: BIAN::DataTypesLibrary::CoreDataTypes::ISO20022andUNCEFACT::Identifier  general-info: Reference to a Service Fees instance retrieve service call   # noqa: E501

        :param service_fees_retrieve_action_task_reference: The service_fees_retrieve_action_task_reference of this InlineResponse2008.
        :type service_fees_retrieve_action_task_reference: str
        """

        self._service_fees_retrieve_action_task_reference = service_fees_retrieve_action_task_reference

    @property
    def service_fees_retrieve_action_task_record(self):
        """Gets the service_fees_retrieve_action_task_record of this InlineResponse2008.

        `status: Not Mapped`  core-data-type-reference: BIAN::DataTypesLibrary::CoreDataTypes::UNCEFACT::Binary  general-info: The retrieve service call consolidated processing record   # noqa: E501

        :return: The service_fees_retrieve_action_task_record of this InlineResponse2008.
        :rtype: object
        """
        return self._service_fees_retrieve_action_task_record

    @service_fees_retrieve_action_task_record.setter
    def service_fees_retrieve_action_task_record(self, service_fees_retrieve_action_task_record):
        """Sets the service_fees_retrieve_action_task_record of this InlineResponse2008.

        `status: Not Mapped`  core-data-type-reference: BIAN::DataTypesLibrary::CoreDataTypes::UNCEFACT::Binary  general-info: The retrieve service call consolidated processing record   # noqa: E501

        :param service_fees_retrieve_action_task_record: The service_fees_retrieve_action_task_record of this InlineResponse2008.
        :type service_fees_retrieve_action_task_record: object
        """

        self._service_fees_retrieve_action_task_record = service_fees_retrieve_action_task_record

    @property
    def service_fees_retrieve_action_response(self):
        """Gets the service_fees_retrieve_action_response of this InlineResponse2008.

        `status: Not Mapped`  core-data-type-reference: BIAN::DataTypesLibrary::CoreDataTypes::UNCEFACT::Text  general-info: Details of the retrieve action service response (lists returned reports)   # noqa: E501

        :return: The service_fees_retrieve_action_response of this InlineResponse2008.
        :rtype: str
        """
        return self._service_fees_retrieve_action_response

    @service_fees_retrieve_action_response.setter
    def service_fees_retrieve_action_response(self, service_fees_retrieve_action_response):
        """Sets the service_fees_retrieve_action_response of this InlineResponse2008.

        `status: Not Mapped`  core-data-type-reference: BIAN::DataTypesLibrary::CoreDataTypes::UNCEFACT::Text  general-info: Details of the retrieve action service response (lists returned reports)   # noqa: E501

        :param service_fees_retrieve_action_response: The service_fees_retrieve_action_response of this InlineResponse2008.
        :type service_fees_retrieve_action_response: str
        """

        self._service_fees_retrieve_action_response = service_fees_retrieve_action_response

    @property
    def service_fees_instance_report(self):
        """Gets the service_fees_instance_report of this InlineResponse2008.


        :return: The service_fees_instance_report of this InlineResponse2008.
        :rtype: InlineResponse2008ServiceFeesInstanceReport
        """
        return self._service_fees_instance_report

    @service_fees_instance_report.setter
    def service_fees_instance_report(self, service_fees_instance_report):
        """Sets the service_fees_instance_report of this InlineResponse2008.


        :param service_fees_instance_report: The service_fees_instance_report of this InlineResponse2008.
        :type service_fees_instance_report: InlineResponse2008ServiceFeesInstanceReport
        """

        self._service_fees_instance_report = service_fees_instance_report

    @property
    def service_fees_instance_analysis(self):
        """Gets the service_fees_instance_analysis of this InlineResponse2008.


        :return: The service_fees_instance_analysis of this InlineResponse2008.
        :rtype: InlineResponse2008ServiceFeesInstanceAnalysis
        """
        return self._service_fees_instance_analysis

    @service_fees_instance_analysis.setter
    def service_fees_instance_analysis(self, service_fees_instance_analysis):
        """Sets the service_fees_instance_analysis of this InlineResponse2008.


        :param service_fees_instance_analysis: The service_fees_instance_analysis of this InlineResponse2008.
        :type service_fees_instance_analysis: InlineResponse2008ServiceFeesInstanceAnalysis
        """

        self._service_fees_instance_analysis = service_fees_instance_analysis
