# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from tester.app.dto.base_model_ import Model
from tester import util




class InlineResponse2008ServiceFeesInstanceRecordFeeConfigurationProfile(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, fee_definition=None, fee_type=None):  # noqa: E501
        """InlineResponse2008ServiceFeesInstanceRecordFeeConfigurationProfile - a model defined in OpenAPI

        :param fee_definition: The fee_definition of this InlineResponse2008ServiceFeesInstanceRecordFeeConfigurationProfile.  # noqa: E501
        :type fee_definition: str
        :param fee_type: The fee_type of this InlineResponse2008ServiceFeesInstanceRecordFeeConfigurationProfile.  # noqa: E501
        :type fee_type: str
        """
        self.openapi_types = {
            'fee_definition': str,
            'fee_type': str
        }

        self.attribute_map = {
            'fee_definition': 'feeDefinition',
            'fee_type': 'feeType'
        }

        self._fee_definition = fee_definition
        self._fee_type = fee_type

    @classmethod
    def from_dict(cls, dikt) -> 'InlineResponse2008ServiceFeesInstanceRecordFeeConfigurationProfile':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The inline_response_200_8_serviceFeesInstanceRecord_feeConfigurationProfile of this InlineResponse2008ServiceFeesInstanceRecordFeeConfigurationProfile.  # noqa: E501
        :rtype: InlineResponse2008ServiceFeesInstanceRecordFeeConfigurationProfile
        """
        return util.deserialize_model(dikt, cls)

    @property
    def fee_definition(self):
        """Gets the fee_definition of this InlineResponse2008ServiceFeesInstanceRecordFeeConfigurationProfile.

        `status: Registered`  iso-link: https://www.iso20022.org/standardsrepository/public/wqt/Description/mx/dico/bc/_Fbg_gMTGEeChad0JzLk7QA_-330542668/elements/_Fbg_hcTGEeChad0JzLk7QA_1324289986  bian-reference: FeeFeature.FeeDefinition  general-info: Definition of the fee or penalty including when and how to apply   # noqa: E501

        :return: The fee_definition of this InlineResponse2008ServiceFeesInstanceRecordFeeConfigurationProfile.
        :rtype: str
        """
        return self._fee_definition

    @fee_definition.setter
    def fee_definition(self, fee_definition):
        """Sets the fee_definition of this InlineResponse2008ServiceFeesInstanceRecordFeeConfigurationProfile.

        `status: Registered`  iso-link: https://www.iso20022.org/standardsrepository/public/wqt/Description/mx/dico/bc/_Fbg_gMTGEeChad0JzLk7QA_-330542668/elements/_Fbg_hcTGEeChad0JzLk7QA_1324289986  bian-reference: FeeFeature.FeeDefinition  general-info: Definition of the fee or penalty including when and how to apply   # noqa: E501

        :param fee_definition: The fee_definition of this InlineResponse2008ServiceFeesInstanceRecordFeeConfigurationProfile.
        :type fee_definition: str
        """

        self._fee_definition = fee_definition

    @property
    def fee_type(self):
        """Gets the fee_type of this InlineResponse2008ServiceFeesInstanceRecordFeeConfigurationProfile.

        `status: Registered`  iso-link: https://www.iso20022.org/standardsrepository/public/wqt/Description/mx/dico/bc/_Fbg_gMTGEeChad0JzLk7QA_-330542668/elements/_Fbg_gcTGEeChad0JzLk7QA_-70110816  bian-reference: FeeFeature.FeeType `status: Registered`  iso-link: https://www.iso20022.org/standardsrepository/public/wqt/Description/mx/dico/bc/_Fbg_gMTGEeChad0JzLk7QA_-330542668/elements/_Fbg_gcTGEeChad0JzLk7QA_-70110816  bian-reference: FeeFeature.FeeType  general-info: The fee or penalty type applied   # noqa: E501

        :return: The fee_type of this InlineResponse2008ServiceFeesInstanceRecordFeeConfigurationProfile.
        :rtype: str
        """
        return self._fee_type

    @fee_type.setter
    def fee_type(self, fee_type):
        """Sets the fee_type of this InlineResponse2008ServiceFeesInstanceRecordFeeConfigurationProfile.

        `status: Registered`  iso-link: https://www.iso20022.org/standardsrepository/public/wqt/Description/mx/dico/bc/_Fbg_gMTGEeChad0JzLk7QA_-330542668/elements/_Fbg_gcTGEeChad0JzLk7QA_-70110816  bian-reference: FeeFeature.FeeType `status: Registered`  iso-link: https://www.iso20022.org/standardsrepository/public/wqt/Description/mx/dico/bc/_Fbg_gMTGEeChad0JzLk7QA_-330542668/elements/_Fbg_gcTGEeChad0JzLk7QA_-70110816  bian-reference: FeeFeature.FeeType  general-info: The fee or penalty type applied   # noqa: E501

        :param fee_type: The fee_type of this InlineResponse2008ServiceFeesInstanceRecordFeeConfigurationProfile.
        :type fee_type: str
        """

        self._fee_type = fee_type
