# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from tester.app.dto.base_model_ import Model
from tester.app.dto.current_account_sd_reference_id_current_account_fulfillment_arrangement_cr_reference_id_issueddevice_initiation_current_account_fulfillment_arrangement_instance_record import CurrentAccountSdReferenceIdCurrentAccountFulfillmentArrangementCrReferenceIdIssueddeviceInitiationCurrentAccountFulfillmentArrangementInstanceRecord
from tester.app.dto.current_account_sd_reference_id_current_account_fulfillment_arrangement_cr_reference_id_issueddevice_initiation_issued_device_instance_record import CurrentAccountSdReferenceIdCurrentAccountFulfillmentArrangementCrReferenceIdIssueddeviceInitiationIssuedDeviceInstanceRecord
from tester import util

from tester.app.dto.current_account_sd_reference_id_current_account_fulfillment_arrangement_cr_reference_id_issueddevice_initiation_current_account_fulfillment_arrangement_instance_record import CurrentAccountSdReferenceIdCurrentAccountFulfillmentArrangementCrReferenceIdIssueddeviceInitiationCurrentAccountFulfillmentArrangementInstanceRecord  # noqa: E501
from tester.app.dto.current_account_sd_reference_id_current_account_fulfillment_arrangement_cr_reference_id_issueddevice_initiation_issued_device_instance_record import CurrentAccountSdReferenceIdCurrentAccountFulfillmentArrangementCrReferenceIdIssueddeviceInitiationIssuedDeviceInstanceRecord  # noqa: E501



class InlineObject21(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, current_account_fulfillment_arrangement_instance_record=None, current_account_fulfillment_arrangement_instance_reference=None, issued_device_initiate_action_record=None, issued_device_instance_record=None):  # noqa: E501
        """InlineObject21 - a model defined in OpenAPI

        :param current_account_fulfillment_arrangement_instance_record: The current_account_fulfillment_arrangement_instance_record of this InlineObject21.  # noqa: E501
        :type current_account_fulfillment_arrangement_instance_record: CurrentAccountSdReferenceIdCurrentAccountFulfillmentArrangementCrReferenceIdIssueddeviceInitiationCurrentAccountFulfillmentArrangementInstanceRecord
        :param current_account_fulfillment_arrangement_instance_reference: The current_account_fulfillment_arrangement_instance_reference of this InlineObject21.  # noqa: E501
        :type current_account_fulfillment_arrangement_instance_reference: str
        :param issued_device_initiate_action_record: The issued_device_initiate_action_record of this InlineObject21.  # noqa: E501
        :type issued_device_initiate_action_record: object
        :param issued_device_instance_record: The issued_device_instance_record of this InlineObject21.  # noqa: E501
        :type issued_device_instance_record: CurrentAccountSdReferenceIdCurrentAccountFulfillmentArrangementCrReferenceIdIssueddeviceInitiationIssuedDeviceInstanceRecord
        """
        self.openapi_types = {
            'current_account_fulfillment_arrangement_instance_record': CurrentAccountSdReferenceIdCurrentAccountFulfillmentArrangementCrReferenceIdIssueddeviceInitiationCurrentAccountFulfillmentArrangementInstanceRecord,
            'current_account_fulfillment_arrangement_instance_reference': str,
            'issued_device_initiate_action_record': object,
            'issued_device_instance_record': CurrentAccountSdReferenceIdCurrentAccountFulfillmentArrangementCrReferenceIdIssueddeviceInitiationIssuedDeviceInstanceRecord
        }

        self.attribute_map = {
            'current_account_fulfillment_arrangement_instance_record': 'currentAccountFulfillmentArrangementInstanceRecord',
            'current_account_fulfillment_arrangement_instance_reference': 'currentAccountFulfillmentArrangementInstanceReference',
            'issued_device_initiate_action_record': 'issuedDeviceInitiateActionRecord',
            'issued_device_instance_record': 'issuedDeviceInstanceRecord'
        }

        self._current_account_fulfillment_arrangement_instance_record = current_account_fulfillment_arrangement_instance_record
        self._current_account_fulfillment_arrangement_instance_reference = current_account_fulfillment_arrangement_instance_reference
        self._issued_device_initiate_action_record = issued_device_initiate_action_record
        self._issued_device_instance_record = issued_device_instance_record

    @classmethod
    def from_dict(cls, dikt) -> 'InlineObject21':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The inline_object_21 of this InlineObject21.  # noqa: E501
        :rtype: InlineObject21
        """
        return util.deserialize_model(dikt, cls)

    @property
    def current_account_fulfillment_arrangement_instance_record(self):
        """Gets the current_account_fulfillment_arrangement_instance_record of this InlineObject21.


        :return: The current_account_fulfillment_arrangement_instance_record of this InlineObject21.
        :rtype: CurrentAccountSdReferenceIdCurrentAccountFulfillmentArrangementCrReferenceIdIssueddeviceInitiationCurrentAccountFulfillmentArrangementInstanceRecord
        """
        return self._current_account_fulfillment_arrangement_instance_record

    @current_account_fulfillment_arrangement_instance_record.setter
    def current_account_fulfillment_arrangement_instance_record(self, current_account_fulfillment_arrangement_instance_record):
        """Sets the current_account_fulfillment_arrangement_instance_record of this InlineObject21.


        :param current_account_fulfillment_arrangement_instance_record: The current_account_fulfillment_arrangement_instance_record of this InlineObject21.
        :type current_account_fulfillment_arrangement_instance_record: CurrentAccountSdReferenceIdCurrentAccountFulfillmentArrangementCrReferenceIdIssueddeviceInitiationCurrentAccountFulfillmentArrangementInstanceRecord
        """

        self._current_account_fulfillment_arrangement_instance_record = current_account_fulfillment_arrangement_instance_record

    @property
    def current_account_fulfillment_arrangement_instance_reference(self):
        """Gets the current_account_fulfillment_arrangement_instance_reference of this InlineObject21.

        `status: Not Mapped`  core-data-type-reference: BIAN::DataTypesLibrary::CoreDataTypes::ISO20022andUNCEFACT::Identifier  general-info: Reference to the parent Current Account Fulfillment Arrangement instance   # noqa: E501

        :return: The current_account_fulfillment_arrangement_instance_reference of this InlineObject21.
        :rtype: str
        """
        return self._current_account_fulfillment_arrangement_instance_reference

    @current_account_fulfillment_arrangement_instance_reference.setter
    def current_account_fulfillment_arrangement_instance_reference(self, current_account_fulfillment_arrangement_instance_reference):
        """Sets the current_account_fulfillment_arrangement_instance_reference of this InlineObject21.

        `status: Not Mapped`  core-data-type-reference: BIAN::DataTypesLibrary::CoreDataTypes::ISO20022andUNCEFACT::Identifier  general-info: Reference to the parent Current Account Fulfillment Arrangement instance   # noqa: E501

        :param current_account_fulfillment_arrangement_instance_reference: The current_account_fulfillment_arrangement_instance_reference of this InlineObject21.
        :type current_account_fulfillment_arrangement_instance_reference: str
        """

        self._current_account_fulfillment_arrangement_instance_reference = current_account_fulfillment_arrangement_instance_reference

    @property
    def issued_device_initiate_action_record(self):
        """Gets the issued_device_initiate_action_record of this InlineObject21.

        `status: Not Mapped`  core-data-type-reference: BIAN::DataTypesLibrary::CoreDataTypes::UNCEFACT::Binary  general-info: The Initiate service call input and output record   # noqa: E501

        :return: The issued_device_initiate_action_record of this InlineObject21.
        :rtype: object
        """
        return self._issued_device_initiate_action_record

    @issued_device_initiate_action_record.setter
    def issued_device_initiate_action_record(self, issued_device_initiate_action_record):
        """Sets the issued_device_initiate_action_record of this InlineObject21.

        `status: Not Mapped`  core-data-type-reference: BIAN::DataTypesLibrary::CoreDataTypes::UNCEFACT::Binary  general-info: The Initiate service call input and output record   # noqa: E501

        :param issued_device_initiate_action_record: The issued_device_initiate_action_record of this InlineObject21.
        :type issued_device_initiate_action_record: object
        """

        self._issued_device_initiate_action_record = issued_device_initiate_action_record

    @property
    def issued_device_instance_record(self):
        """Gets the issued_device_instance_record of this InlineObject21.


        :return: The issued_device_instance_record of this InlineObject21.
        :rtype: CurrentAccountSdReferenceIdCurrentAccountFulfillmentArrangementCrReferenceIdIssueddeviceInitiationIssuedDeviceInstanceRecord
        """
        return self._issued_device_instance_record

    @issued_device_instance_record.setter
    def issued_device_instance_record(self, issued_device_instance_record):
        """Sets the issued_device_instance_record of this InlineObject21.


        :param issued_device_instance_record: The issued_device_instance_record of this InlineObject21.
        :type issued_device_instance_record: CurrentAccountSdReferenceIdCurrentAccountFulfillmentArrangementCrReferenceIdIssueddeviceInitiationIssuedDeviceInstanceRecord
        """

        self._issued_device_instance_record = issued_device_instance_record
