# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from tester.app.dto.base_model_ import Model
from tester.app.dto.current_account_sd_reference_id_current_account_fulfillment_arrangement_initiation_current_account_fulfillment_arrangement_instance_record_date_type import CurrentAccountSdReferenceIdCurrentAccountFulfillmentArrangementInitiationCurrentAccountFulfillmentArrangementInstanceRecordDateType
from tester.app.dto.inline_response2015_current_account_fulfillment_arrangement_instance_record_position_limits import InlineResponse2015CurrentAccountFulfillmentArrangementInstanceRecordPositionLimits
from tester import util

from tester.app.dto.current_account_sd_reference_id_current_account_fulfillment_arrangement_initiation_current_account_fulfillment_arrangement_instance_record_date_type import CurrentAccountSdReferenceIdCurrentAccountFulfillmentArrangementInitiationCurrentAccountFulfillmentArrangementInstanceRecordDateType  # noqa: E501
from tester.app.dto.inline_response2015_current_account_fulfillment_arrangement_instance_record_position_limits import InlineResponse2015CurrentAccountFulfillmentArrangementInstanceRecordPositionLimits  # noqa: E501



class InlineResponse2015CurrentAccountFulfillmentArrangementInstanceRecord(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, position_limits=None, date_type=None):  # noqa: E501
        """InlineResponse2015CurrentAccountFulfillmentArrangementInstanceRecord - a model defined in OpenAPI

        :param position_limits: The position_limits of this InlineResponse2015CurrentAccountFulfillmentArrangementInstanceRecord.  # noqa: E501
        :type position_limits: InlineResponse2015CurrentAccountFulfillmentArrangementInstanceRecordPositionLimits
        :param date_type: The date_type of this InlineResponse2015CurrentAccountFulfillmentArrangementInstanceRecord.  # noqa: E501
        :type date_type: CurrentAccountSdReferenceIdCurrentAccountFulfillmentArrangementInitiationCurrentAccountFulfillmentArrangementInstanceRecordDateType
        """
        self.openapi_types = {
            'position_limits': InlineResponse2015CurrentAccountFulfillmentArrangementInstanceRecordPositionLimits,
            'date_type': CurrentAccountSdReferenceIdCurrentAccountFulfillmentArrangementInitiationCurrentAccountFulfillmentArrangementInstanceRecordDateType
        }

        self.attribute_map = {
            'position_limits': 'positionLimits',
            'date_type': 'dateType'
        }

        self._position_limits = position_limits
        self._date_type = date_type

    @classmethod
    def from_dict(cls, dikt) -> 'InlineResponse2015CurrentAccountFulfillmentArrangementInstanceRecord':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The inline_response_201_5_currentAccountFulfillmentArrangementInstanceRecord of this InlineResponse2015CurrentAccountFulfillmentArrangementInstanceRecord.  # noqa: E501
        :rtype: InlineResponse2015CurrentAccountFulfillmentArrangementInstanceRecord
        """
        return util.deserialize_model(dikt, cls)

    @property
    def position_limits(self):
        """Gets the position_limits of this InlineResponse2015CurrentAccountFulfillmentArrangementInstanceRecord.


        :return: The position_limits of this InlineResponse2015CurrentAccountFulfillmentArrangementInstanceRecord.
        :rtype: InlineResponse2015CurrentAccountFulfillmentArrangementInstanceRecordPositionLimits
        """
        return self._position_limits

    @position_limits.setter
    def position_limits(self, position_limits):
        """Sets the position_limits of this InlineResponse2015CurrentAccountFulfillmentArrangementInstanceRecord.


        :param position_limits: The position_limits of this InlineResponse2015CurrentAccountFulfillmentArrangementInstanceRecord.
        :type position_limits: InlineResponse2015CurrentAccountFulfillmentArrangementInstanceRecordPositionLimits
        """

        self._position_limits = position_limits

    @property
    def date_type(self):
        """Gets the date_type of this InlineResponse2015CurrentAccountFulfillmentArrangementInstanceRecord.


        :return: The date_type of this InlineResponse2015CurrentAccountFulfillmentArrangementInstanceRecord.
        :rtype: CurrentAccountSdReferenceIdCurrentAccountFulfillmentArrangementInitiationCurrentAccountFulfillmentArrangementInstanceRecordDateType
        """
        return self._date_type

    @date_type.setter
    def date_type(self, date_type):
        """Sets the date_type of this InlineResponse2015CurrentAccountFulfillmentArrangementInstanceRecord.


        :param date_type: The date_type of this InlineResponse2015CurrentAccountFulfillmentArrangementInstanceRecord.
        :type date_type: CurrentAccountSdReferenceIdCurrentAccountFulfillmentArrangementInitiationCurrentAccountFulfillmentArrangementInstanceRecordDateType
        """

        self._date_type = date_type
