# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from tester.app.dto.base_model_ import Model
from tester.app.dto.current_account_sd_reference_id_current_account_fulfillment_arrangement_cr_reference_id_update_current_account_fulfillment_arrangement_instance_record import CurrentAccountSdReferenceIdCurrentAccountFulfillmentArrangementCrReferenceIdUpdateCurrentAccountFulfillmentArrangementInstanceRecord
from tester import util

from tester.app.dto.current_account_sd_reference_id_current_account_fulfillment_arrangement_cr_reference_id_update_current_account_fulfillment_arrangement_instance_record import CurrentAccountSdReferenceIdCurrentAccountFulfillmentArrangementCrReferenceIdUpdateCurrentAccountFulfillmentArrangementInstanceRecord  # noqa: E501



class InlineObject4(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, current_account_servicing_session_reference=None, current_account_fulfillment_arrangement_instance_reference=None, current_account_fulfillment_arrangement_instance_record=None, current_account_fulfillment_arrangement_update_action_task_record=None, update_action_request=None):  # noqa: E501
        """InlineObject4 - a model defined in OpenAPI

        :param current_account_servicing_session_reference: The current_account_servicing_session_reference of this InlineObject4.  # noqa: E501
        :type current_account_servicing_session_reference: str
        :param current_account_fulfillment_arrangement_instance_reference: The current_account_fulfillment_arrangement_instance_reference of this InlineObject4.  # noqa: E501
        :type current_account_fulfillment_arrangement_instance_reference: str
        :param current_account_fulfillment_arrangement_instance_record: The current_account_fulfillment_arrangement_instance_record of this InlineObject4.  # noqa: E501
        :type current_account_fulfillment_arrangement_instance_record: CurrentAccountSdReferenceIdCurrentAccountFulfillmentArrangementCrReferenceIdUpdateCurrentAccountFulfillmentArrangementInstanceRecord
        :param current_account_fulfillment_arrangement_update_action_task_record: The current_account_fulfillment_arrangement_update_action_task_record of this InlineObject4.  # noqa: E501
        :type current_account_fulfillment_arrangement_update_action_task_record: object
        :param update_action_request: The update_action_request of this InlineObject4.  # noqa: E501
        :type update_action_request: str
        """
        self.openapi_types = {
            'current_account_servicing_session_reference': str,
            'current_account_fulfillment_arrangement_instance_reference': str,
            'current_account_fulfillment_arrangement_instance_record': CurrentAccountSdReferenceIdCurrentAccountFulfillmentArrangementCrReferenceIdUpdateCurrentAccountFulfillmentArrangementInstanceRecord,
            'current_account_fulfillment_arrangement_update_action_task_record': object,
            'update_action_request': str
        }

        self.attribute_map = {
            'current_account_servicing_session_reference': 'currentAccountServicingSessionReference',
            'current_account_fulfillment_arrangement_instance_reference': 'currentAccountFulfillmentArrangementInstanceReference',
            'current_account_fulfillment_arrangement_instance_record': 'currentAccountFulfillmentArrangementInstanceRecord',
            'current_account_fulfillment_arrangement_update_action_task_record': 'currentAccountFulfillmentArrangementUpdateActionTaskRecord',
            'update_action_request': 'updateActionRequest'
        }

        self._current_account_servicing_session_reference = current_account_servicing_session_reference
        self._current_account_fulfillment_arrangement_instance_reference = current_account_fulfillment_arrangement_instance_reference
        self._current_account_fulfillment_arrangement_instance_record = current_account_fulfillment_arrangement_instance_record
        self._current_account_fulfillment_arrangement_update_action_task_record = current_account_fulfillment_arrangement_update_action_task_record
        self._update_action_request = update_action_request

    @classmethod
    def from_dict(cls, dikt) -> 'InlineObject4':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The inline_object_4 of this InlineObject4.  # noqa: E501
        :rtype: InlineObject4
        """
        return util.deserialize_model(dikt, cls)

    @property
    def current_account_servicing_session_reference(self):
        """Gets the current_account_servicing_session_reference of this InlineObject4.

        `status: Not Mapped`  core-data-type-reference: BIAN::DataTypesLibrary::CoreDataTypes::ISO20022andUNCEFACT::Identifier  general-info: Reference to the active servicing session   # noqa: E501

        :return: The current_account_servicing_session_reference of this InlineObject4.
        :rtype: str
        """
        return self._current_account_servicing_session_reference

    @current_account_servicing_session_reference.setter
    def current_account_servicing_session_reference(self, current_account_servicing_session_reference):
        """Sets the current_account_servicing_session_reference of this InlineObject4.

        `status: Not Mapped`  core-data-type-reference: BIAN::DataTypesLibrary::CoreDataTypes::ISO20022andUNCEFACT::Identifier  general-info: Reference to the active servicing session   # noqa: E501

        :param current_account_servicing_session_reference: The current_account_servicing_session_reference of this InlineObject4.
        :type current_account_servicing_session_reference: str
        """

        self._current_account_servicing_session_reference = current_account_servicing_session_reference

    @property
    def current_account_fulfillment_arrangement_instance_reference(self):
        """Gets the current_account_fulfillment_arrangement_instance_reference of this InlineObject4.

        `status: Not Mapped`  core-data-type-reference: BIAN::DataTypesLibrary::CoreDataTypes::ISO20022andUNCEFACT::Identifier  general-info: Reference to the Current Account Fulfillment Arrangement instance   # noqa: E501

        :return: The current_account_fulfillment_arrangement_instance_reference of this InlineObject4.
        :rtype: str
        """
        return self._current_account_fulfillment_arrangement_instance_reference

    @current_account_fulfillment_arrangement_instance_reference.setter
    def current_account_fulfillment_arrangement_instance_reference(self, current_account_fulfillment_arrangement_instance_reference):
        """Sets the current_account_fulfillment_arrangement_instance_reference of this InlineObject4.

        `status: Not Mapped`  core-data-type-reference: BIAN::DataTypesLibrary::CoreDataTypes::ISO20022andUNCEFACT::Identifier  general-info: Reference to the Current Account Fulfillment Arrangement instance   # noqa: E501

        :param current_account_fulfillment_arrangement_instance_reference: The current_account_fulfillment_arrangement_instance_reference of this InlineObject4.
        :type current_account_fulfillment_arrangement_instance_reference: str
        """

        self._current_account_fulfillment_arrangement_instance_reference = current_account_fulfillment_arrangement_instance_reference

    @property
    def current_account_fulfillment_arrangement_instance_record(self):
        """Gets the current_account_fulfillment_arrangement_instance_record of this InlineObject4.


        :return: The current_account_fulfillment_arrangement_instance_record of this InlineObject4.
        :rtype: CurrentAccountSdReferenceIdCurrentAccountFulfillmentArrangementCrReferenceIdUpdateCurrentAccountFulfillmentArrangementInstanceRecord
        """
        return self._current_account_fulfillment_arrangement_instance_record

    @current_account_fulfillment_arrangement_instance_record.setter
    def current_account_fulfillment_arrangement_instance_record(self, current_account_fulfillment_arrangement_instance_record):
        """Sets the current_account_fulfillment_arrangement_instance_record of this InlineObject4.


        :param current_account_fulfillment_arrangement_instance_record: The current_account_fulfillment_arrangement_instance_record of this InlineObject4.
        :type current_account_fulfillment_arrangement_instance_record: CurrentAccountSdReferenceIdCurrentAccountFulfillmentArrangementCrReferenceIdUpdateCurrentAccountFulfillmentArrangementInstanceRecord
        """

        self._current_account_fulfillment_arrangement_instance_record = current_account_fulfillment_arrangement_instance_record

    @property
    def current_account_fulfillment_arrangement_update_action_task_record(self):
        """Gets the current_account_fulfillment_arrangement_update_action_task_record of this InlineObject4.

        `status: Not Mapped`  core-data-type-reference: BIAN::DataTypesLibrary::CoreDataTypes::UNCEFACT::Binary  general-info: The update service call consolidated processing record   # noqa: E501

        :return: The current_account_fulfillment_arrangement_update_action_task_record of this InlineObject4.
        :rtype: object
        """
        return self._current_account_fulfillment_arrangement_update_action_task_record

    @current_account_fulfillment_arrangement_update_action_task_record.setter
    def current_account_fulfillment_arrangement_update_action_task_record(self, current_account_fulfillment_arrangement_update_action_task_record):
        """Sets the current_account_fulfillment_arrangement_update_action_task_record of this InlineObject4.

        `status: Not Mapped`  core-data-type-reference: BIAN::DataTypesLibrary::CoreDataTypes::UNCEFACT::Binary  general-info: The update service call consolidated processing record   # noqa: E501

        :param current_account_fulfillment_arrangement_update_action_task_record: The current_account_fulfillment_arrangement_update_action_task_record of this InlineObject4.
        :type current_account_fulfillment_arrangement_update_action_task_record: object
        """

        self._current_account_fulfillment_arrangement_update_action_task_record = current_account_fulfillment_arrangement_update_action_task_record

    @property
    def update_action_request(self):
        """Gets the update_action_request of this InlineObject4.

        `status: Not Mapped`  core-data-type-reference: BIAN::DataTypesLibrary::CoreDataTypes::UNCEFACT::Text  general-info: Details of the update action service request   # noqa: E501

        :return: The update_action_request of this InlineObject4.
        :rtype: str
        """
        return self._update_action_request

    @update_action_request.setter
    def update_action_request(self, update_action_request):
        """Sets the update_action_request of this InlineObject4.

        `status: Not Mapped`  core-data-type-reference: BIAN::DataTypesLibrary::CoreDataTypes::UNCEFACT::Text  general-info: Details of the update action service request   # noqa: E501

        :param update_action_request: The update_action_request of this InlineObject4.
        :type update_action_request: str
        """

        self._update_action_request = update_action_request
